#!/usr/bin/env bash
# Regenerates the shimmed copy of VisionCoreContracts.swift used by the Linux
# harness. Its only Apple-only dependency is `import CoreVideo` for the
# CVPixelBuffer type in two protocol signatures. Production sources are never
# edited: the copy lives under this harness and is derived on every run.
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
src="$here/../../Sources/VisionCoreContracts.swift"
out="$here/Sources/VisionCoreContracts.swift"
{
  echo "// GENERATED by audit/linux-harness/generate-contracts.sh from ../../Sources/VisionCoreContracts.swift — do not edit."
  echo "#if canImport(CoreVideo)"
  echo "import CoreVideo"
  echo "#else"
  echo "/// Linux shim: CVPixelBuffer only appears in protocol signatures here."
  echo "public typealias CVPixelBuffer = AnyObject"
  echo "#endif"
  grep -v '^import CoreVideo$' "$src"
} > "$out"
# Guard: the copy must differ from the canonical file ONLY by the shim header.
diff <(grep -v '^import CoreVideo$' "$src") <(tail -n +8 "$out") >/dev/null
