#!/usr/bin/env python3
"""Generate a frozen integration-adversary fan-out launcher.

    python3 .devin/skills/production-program/make_adversary_launcher.py <HEAD_SHA> <FANOUT_ID> \
        [--areas a,b,c] [--branch INTEGRATION_BRANCH] [--mode MODE] [--minutes N]

Writes .devin/program/runs/ADV__<sha12>__<fanout_id>.py — one independent adversary per
production area (program_lib.INTEGRATION_AREAS) against the frozen integration head.
Run it with the run_workflow tool. Nothing in the fan-out mutates the integration branch.
"""

from __future__ import annotations

import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
LEDGER_ROOT = os.path.join(ROOT, ".devin", "program", "ledger")
INTEGRATION_BRANCH = "devin/1788854799-production-program-integration"

TEMPLATE = '''"""Frozen integration-adversary launcher — generated by make_adversary_launcher.py; do not hand-edit."""
import asyncio
import sys

sys.path.insert(0, {lib_dir!r})
import program_lib  # noqa: E402

FANOUT_ID = {fanout_id!r}
HEAD_SHA = {head_sha!r}
INTEGRATION_BRANCH = {integration_branch!r}
OUT_ROOT = {out_root!r}
MODE = {mode!r}
MINUTES = {minutes!r}
AREAS = {areas!r}
LIB_VERSION = {lib_version!r}


async def main():
    if program_lib.LIB_VERSION != LIB_VERSION:
        raise SystemExit("program_lib changed since this launcher was frozen; regenerate the launcher")
    runtime = program_lib.Runtime(
        register_workflow=register_workflow,
        agent=agent,
        log=log,
        agent_error=WorkflowAgentError,
    )
    summary = await program_lib.run_adversary_fanout(
        fanout_id=FANOUT_ID,
        head_sha=HEAD_SHA,
        integration_branch=INTEGRATION_BRANCH,
        out_root=OUT_ROOT,
        runtime=runtime,
        areas=AREAS,
        mode=MODE,
        minutes=MINUTES,
    )
    log("ADVERSARY FANOUT RESULT " + program_lib.dump(summary))


asyncio.run(main())
'''


def make(head_sha: str, fanout_id: str, *, areas: list[str] | None, integration_branch: str = INTEGRATION_BRANCH, mode: str | None = None, minutes: int = 60) -> str:
    sys.path.insert(0, HERE)
    import program_lib  # noqa: E402

    if not program_lib.SHA_RE.match(head_sha):
        raise SystemExit("head sha must be 40 hex")
    if not fanout_id or "/" in fanout_id:
        raise SystemExit("fanout id must be a non-empty path segment")
    chosen = list(areas) if areas else list(program_lib.INTEGRATION_AREAS)
    unknown = [a for a in chosen if a not in program_lib.INTEGRATION_AREAS]
    if unknown:
        raise SystemExit(f"unknown areas: {unknown}; known: {sorted(program_lib.INTEGRATION_AREAS)}")
    if len(set(chosen)) != len(chosen):
        raise SystemExit("duplicate areas")
    if not 1 <= minutes <= 60:
        raise SystemExit("--minutes must be within 1..60")
    out_dir = os.path.join(ROOT, ".devin", "program", "runs")
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, f"ADV__{head_sha[:12]}__{fanout_id}.py")
    with open(path, "w", encoding="utf8") as fh:
        fh.write(
            TEMPLATE.format(
                lib_dir=HERE,
                fanout_id=fanout_id,
                head_sha=head_sha,
                integration_branch=integration_branch,
                out_root=LEDGER_ROOT,
                mode=mode,
                minutes=minutes,
                areas=chosen,
                lib_version=program_lib.LIB_VERSION,
            )
        )
    return path


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("head_sha")
    ap.add_argument("fanout_id")
    ap.add_argument("--areas", default="", help="comma-separated area ids (default: every area)")
    ap.add_argument("--branch", default=INTEGRATION_BRANCH)
    ap.add_argument("--mode", default=None)
    ap.add_argument("--minutes", type=int, default=60)
    a = ap.parse_args()
    areas = [x for x in a.areas.split(",") if x] or None
    print(make(a.head_sha, a.fanout_id, areas=areas, integration_branch=a.branch, mode=a.mode, minutes=a.minutes))


if __name__ == "__main__":
    main()
