#!/usr/bin/env python3
"""Generate a candidate-verification launcher for a Mac-plane package.

    python3 .devin/skills/production-program/make_verify_launcher.py <PKG> <WAVE_ID> \
        --record <prior record.json> --round N --head-sha <candidate sha> \
        --evidence <criterion id>=<mac-full-verify run.json> [--branch INTEGRATION_BRANCH]

The prior record's implementer result for --round is reused as the candidate claim;
its `head_sha` is replaced by --head-sha when the coordinator added a fix commit on the
same candidate branch. Every manual criterion named in --evidence is filled from the
coordinator's own exact-SHA `scripts/mac-full-verify.sh --remote` artifact (run.json
must say conclusion=success on that sha and the sibling summary.json ok=true), and the
same evidence is handed to the independent reviewer and adversary. Writes
.devin/program/runs/VERIFY__<sha12>__<wave_id>.py — run it with run_workflow.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
sys.path.insert(0, HERE)
import program_lib  # noqa: E402

LEDGER_ROOT = os.path.join(ROOT, ".devin", "program", "ledger")
INTEGRATION_BRANCH = "devin/1788854799-production-program-integration"
SHA_RE = re.compile(r"^[0-9a-f]{40}$")

TEMPLATE = '''"""Frozen candidate-verification launcher — generated by make_verify_launcher.py; do not hand-edit."""
import asyncio
import sys

sys.path.insert(0, {lib_dir!r})
import program_lib  # noqa: E402

PACKAGE_ID = {package_id!r}
WAVE_ID = {wave_id!r}
BASE_SHA = {base_sha!r}
INTEGRATION_BRANCH = {integration_branch!r}
MANIFEST = {manifest!r}
OUT_ROOT = {out_root!r}
MODE = {mode!r}
IMPL = {impl!r}
EVIDENCE = {evidence!r}
LIB_VERSION = {lib_version!r}


async def main():
    if program_lib.LIB_VERSION != LIB_VERSION:
        raise SystemExit(f"program_lib {{program_lib.LIB_VERSION}} != launcher {{LIB_VERSION}}; regenerate")
    runtime = program_lib.Runtime(register_workflow=register_workflow, agent=agent, log=log, agent_error=AgentError)
    record = await program_lib.run_candidate_verification(
        package_id=PACKAGE_ID,
        base_sha=BASE_SHA,
        integration_branch=INTEGRATION_BRANCH,
        manifest_path=MANIFEST,
        out_root=OUT_ROOT,
        runtime=runtime,
        wave_id=WAVE_ID,
        impl=IMPL,
        coordinator_evidence=EVIDENCE,
        mode=MODE,
    )
    log("VERIFY RESULT " + program_lib.dump({{"package_id": PACKAGE_ID, "status": record["status"], "candidate": record.get("candidate")}}))


asyncio.run(main())
'''


def load_evidence(criterion_id: str, run_json_path: str, head_sha: str) -> dict:
    with open(run_json_path, encoding="utf8") as fh:
        run = json.load(fh)
    summary_path = os.path.join(os.path.dirname(run_json_path), "summary.json")
    with open(summary_path, encoding="utf8") as fh:
        summary = json.load(fh)
    if run.get("conclusion") != "success" or str(run.get("headSha", "")).lower() != head_sha:
        raise SystemExit(f"{run_json_path}: conclusion={run.get('conclusion')} headSha={run.get('headSha')} does not prove {head_sha}")
    if summary.get("ok") is not True or str(summary.get("git_sha", "")).lower() != head_sha:
        raise SystemExit(f"{summary_path}: ok={summary.get('ok')} git_sha={summary.get('git_sha')} does not prove {head_sha}")
    failed = [s["name"] for s in summary.get("stages", []) if s.get("status") != "passed"]
    if failed:
        raise SystemExit(f"{summary_path}: stages not passed: {failed}")
    rel = os.path.relpath(run_json_path, ROOT)
    return {
        "criterion_id": criterion_id,
        "head_sha": head_sha,
        "run_url": run["url"],
        "run_id": run["databaseId"],
        "run_json": rel,
        "summary_json": os.path.relpath(summary_path, ROOT),
        "stages": summary["stages"],
        "xcode": summary.get("xcode"),
        "host": summary.get("host"),
    }


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("package_id")
    ap.add_argument("wave_id")
    ap.add_argument("--record", required=True)
    ap.add_argument("--round", type=int, required=True)
    ap.add_argument("--head-sha", required=True)
    ap.add_argument("--evidence", action="append", default=[], metavar="CRITERION=RUN_JSON", required=True)
    ap.add_argument("--branch", default=INTEGRATION_BRANCH)
    ap.add_argument("--mode", default=None)
    a = ap.parse_args()
    head = a.head_sha.lower()
    if not SHA_RE.match(head):
        raise SystemExit("--head-sha must be 40 hex")
    with open(a.record, encoding="utf8") as fh:
        record = json.load(fh)
    if record.get("package_id") != a.package_id:
        raise SystemExit(f"{a.record} is for {record.get('package_id')}, not {a.package_id}")
    rnd = next((r for r in record.get("rounds", []) if r.get("round") == a.round), None)
    if rnd is None or not rnd.get("implement"):
        raise SystemExit(f"round {a.round} has no implementer result in {a.record}")
    impl = dict(rnd["implement"])
    impl["round"] = a.round
    impl["head_sha"] = head
    if impl.get("blocked"):
        impl["blocked"] = False
        impl["blocked_reason"] = ""
    evidence: list[dict] = []
    manifest = program_lib.load_manifest(os.path.join(ROOT, ".devin", "program", "manifest.json"))
    pkg = program_lib.find_package(manifest, a.package_id)
    manual = {c["id"]: c for c in pkg["acceptance"] if c["kind"] == "manual"}
    for item in a.evidence:
        cid, _, path = item.partition("=")
        if cid not in manual:
            raise SystemExit(f"{cid} is not a manual criterion of {a.package_id}: {sorted(manual)}")
        ev = load_evidence(cid, os.path.abspath(path), head)
        evidence.append(ev)
        results = [r for r in impl.get("acceptance_results", []) if r.get("id") != cid]
        results.append(
            {
                "id": cid,
                "status": "PASS",
                "command": manual[cid]["command"],
                "exit_code": 0,
                "executed": 0,
                "passed": 0,
                "failed": 0,
                "skipped": 0,
                "artifact": ev["run_url"],
                "note": f"Coordinator-owned Mac slot: GitHub Actions run {ev['run_id']} conclusion=success on exactly {head}; summary.json ok=true, stages {[s['name'] + ':' + s['status'] for s in ev['stages']]}; copies in {ev['run_json']} and {ev['summary_json']}.",
            }
        )
        impl["acceptance_results"] = results
    missing = sorted(set(manual) - {e["criterion_id"] for e in evidence})
    if missing:
        raise SystemExit(f"manual criteria without coordinator evidence: {missing}")
    pre = program_lib.grade_acceptance(pkg, impl["acceptance_results"])
    if pre:
        raise SystemExit(f"candidate claims still incomplete: {pre}")
    base_sha = record["base_sha"]
    out = os.path.join(ROOT, ".devin", "program", "runs", f"VERIFY__{head[:12]}__{a.wave_id}.py")
    with open(out, "w", encoding="utf8") as fh:
        fh.write(
            TEMPLATE.format(
                lib_dir=HERE,
                package_id=a.package_id,
                wave_id=a.wave_id,
                base_sha=base_sha,
                integration_branch=a.branch,
                manifest=os.path.join(ROOT, ".devin", "program", "manifest.json"),
                out_root=os.path.join(ROOT, ".devin", "program", "ledger"),
                mode=a.mode,
                impl=impl,
                evidence=evidence,
                lib_version=program_lib.LIB_VERSION,
            )
        )
    print(out)


if __name__ == "__main__":
    main()
