"""Generate a frozen per-package launcher for `run_workflow`.

    python3 .devin/skills/production-program/make_launcher.py <PKG_ID> <BASE_SHA> <WAVE_ID> \
        [--branch INTEGRATION_BRANCH] [--mode MODE] [--rounds N] [--requeue-from RECORD_JSON]

INTEGRATION_BRANCH (default codex/production-continuation-20260907) must
contain BASE_SHA on origin — children start with `git fetch origin <branch>
&& git checkout <sha>`. Writes `.devin/program/runs/<pkg>__<base12>__<wave>.py`.
The launcher embeds the package id, base sha, integration branch, manifest
hash, wave id and (for a requeue) the prior round's findings and the next
round number as constants so a resumed run replays byte-for-byte; nothing is
read from the clock, environment or network at orchestration time.

Ledger records land under `.devin/program/ledger/<pkg>/<wave>/record.json`
(tracked in git, unlike artifacts/).
"""

from __future__ import annotations

import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
MANIFEST = os.path.join(ROOT, ".devin", "program", "manifest.json")
LEDGER_ROOT = os.path.join(ROOT, ".devin", "program", "ledger")
INTEGRATION_BRANCH = "codex/production-continuation-20260907"

TEMPLATE = '''"""Frozen launcher — generated by make_launcher.py; do not hand-edit."""
import asyncio
import sys

sys.path.insert(0, {lib_dir!r})
import program_lib  # noqa: E402

PACKAGE_ID = {package_id!r}
BASE_SHA = {base_sha!r}
INTEGRATION_BRANCH = {integration_branch!r}
MANIFEST_PATH = {manifest_path!r}
MANIFEST_SHA256 = {manifest_sha!r}
OUT_ROOT = {out_root!r}
WAVE_ID = {wave_id!r}
MAX_ROUNDS = {max_rounds}
MODE = {mode!r}
START_ROUND = {start_round}
PRIOR = {prior!r}


async def main():
    manifest = program_lib.load_manifest(MANIFEST_PATH)
    if manifest["manifest_sha256"] != MANIFEST_SHA256:
        raise SystemExit("manifest changed since this launcher was frozen; regenerate the launcher")
    runtime = program_lib.Runtime(
        register_workflow=register_workflow,
        agent=agent,
        log=log,
        agent_error=WorkflowAgentError,
    )
    record = await program_lib.run_package(
        package_id=PACKAGE_ID,
        base_sha=BASE_SHA,
        integration_branch=INTEGRATION_BRANCH,
        manifest_path=MANIFEST_PATH,
        out_root=OUT_ROOT,
        runtime=runtime,
        max_rounds=MAX_ROUNDS,
        mode=MODE,
        wave_id=WAVE_ID,
        start_round=START_ROUND,
        prior=PRIOR,
    )
    log("RESULT " + program_lib.dump({{k: record.get(k) for k in ("package_id", "status", "candidate", "agent_counts")}}))


asyncio.run(main())
'''


def make(
    package_id: str,
    base_sha: str,
    wave_id: str,
    *,
    integration_branch: str = INTEGRATION_BRANCH,
    max_rounds: int = 2,
    mode: str | None = None,
    requeue_from: str | None = None,
) -> str:
    sys.path.insert(0, HERE)
    import program_lib  # noqa: E402

    manifest = program_lib.load_manifest(MANIFEST)
    pkg = program_lib.find_package(manifest, package_id)
    if pkg["plane"] in ("external", "docs"):
        raise SystemExit(f"{package_id} is {pkg['plane']}-plane; not launchable")
    if not program_lib.SHA_RE.match(base_sha):
        raise SystemExit("base sha must be 40 hex")
    if not wave_id or "/" in wave_id:
        raise SystemExit("wave id must be a non-empty path segment")
    prior: dict | None = None
    start_round = 1
    if requeue_from:
        with open(requeue_from, encoding="utf8") as fh:
            record = json.load(fh)
        if record.get("package_id") != package_id:
            raise SystemExit(f"record {requeue_from} is for {record.get('package_id')}, not {package_id}")
        if record.get("status") != "REQUEUE":
            raise SystemExit(f"record status is {record.get('status')}; only REQUEUE records can be requeued")
        prior, start_round = program_lib.prior_from_record(record)
    out_dir = os.path.join(ROOT, ".devin", "program", "runs")
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, f"{package_id}__{base_sha[:12]}__{wave_id}.py")
    with open(path, "w", encoding="utf8") as fh:
        fh.write(
            TEMPLATE.format(
                lib_dir=HERE,
                package_id=package_id,
                base_sha=base_sha,
                integration_branch=integration_branch,
                manifest_path=MANIFEST,
                manifest_sha=manifest["manifest_sha256"],
                out_root=LEDGER_ROOT,
                wave_id=wave_id,
                max_rounds=max_rounds,
                mode=mode,
                start_round=start_round,
                prior=prior,
            )
        )
    return path


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("package_id")
    ap.add_argument("base_sha")
    ap.add_argument("wave_id")
    ap.add_argument("--branch", default=INTEGRATION_BRANCH)
    ap.add_argument("--mode", default=None)
    ap.add_argument("--rounds", type=int, default=2)
    ap.add_argument("--requeue-from", default=None)
    a = ap.parse_args()
    print(make(a.package_id, a.base_sha, a.wave_id, integration_branch=a.branch, mode=a.mode, max_rounds=a.rounds, requeue_from=a.requeue_from))
