"""Generate a frozen WAVE launcher: many packages concurrently in ONE `run_workflow` run.

    python3 .devin/skills/production-program/make_wave_launcher.py <BASE_SHA> <WAVE_ID> \
        --pkgs W01-02,W04-01,... [--branch INTEGRATION_BRANCH] [--rounds N] [--mode MODE] \
        [--requeue PKG=path/to/record.json ...]

Every package gets its own implementer → (reviewer ‖ adversary) → judge
pipeline inside the same run, so a wave of 20 packages runs up to 40 agents
at once instead of one package after another. `--requeue` freezes the prior
round's blocking findings and continues that package's round numbering. The
package list, base sha, manifest hash and findings are embedded as constants
so a resumed run replays byte-for-byte. Records land under
`.devin/program/ledger/<pkg>/<wave>/record.json` plus
`.devin/program/ledger/_waves/<wave>.json`.
"""

from __future__ import annotations

import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
MANIFEST = os.path.join(ROOT, ".devin", "program", "manifest.json")
LEDGER_ROOT = os.path.join(ROOT, ".devin", "program", "ledger")
INTEGRATION_BRANCH = "codex/production-continuation-20260907"

TEMPLATE = '''"""Frozen wave launcher — generated by make_wave_launcher.py; do not hand-edit."""
import asyncio
import sys

sys.path.insert(0, {lib_dir!r})
import program_lib  # noqa: E402

WAVE_ID = {wave_id!r}
BASE_SHA = {base_sha!r}
INTEGRATION_BRANCH = {integration_branch!r}
MANIFEST_PATH = {manifest_path!r}
MANIFEST_SHA256 = {manifest_sha!r}
OUT_ROOT = {out_root!r}
MODE = {mode!r}
SERIAL_GROUP_LIMIT = {serial_group_limit!r}
PACKAGES = {packages!r}


async def main():
    manifest = program_lib.load_manifest(MANIFEST_PATH)
    if manifest["manifest_sha256"] != MANIFEST_SHA256:
        raise SystemExit("manifest changed since this launcher was frozen; regenerate the launcher")
    runtime = program_lib.Runtime(
        register_workflow=register_workflow,
        agent=agent,
        log=log,
        agent_error=WorkflowAgentError,
    )
    summary = await program_lib.run_wave(
        wave_id=WAVE_ID,
        packages=PACKAGES,
        base_sha=BASE_SHA,
        integration_branch=INTEGRATION_BRANCH,
        manifest_path=MANIFEST_PATH,
        out_root=OUT_ROOT,
        runtime=runtime,
        mode=MODE,
        serial_group_limit=SERIAL_GROUP_LIMIT,
    )
    log("WAVE RESULT " + program_lib.dump(summary))


asyncio.run(main())
'''


def make(
    base_sha: str,
    wave_id: str,
    package_ids: list[str],
    *,
    integration_branch: str = INTEGRATION_BRANCH,
    max_rounds: int = 2,
    mode: str | None = None,
    requeue: dict[str, str] | None = None,
    requeue_blocked: dict[str, str] | None = None,
    serial_group_limit: int = 1,
) -> str:
    sys.path.insert(0, HERE)
    import program_lib  # noqa: E402

    manifest = program_lib.load_manifest(MANIFEST)
    if not program_lib.SHA_RE.match(base_sha):
        raise SystemExit("base sha must be 40 hex")
    if not wave_id or "/" in wave_id:
        raise SystemExit("wave id must be a non-empty path segment")
    if not package_ids:
        raise SystemExit("at least one package id is required")
    requeue = requeue or {}
    requeue_blocked = requeue_blocked or {}
    unknown = (set(requeue) | set(requeue_blocked)) - set(package_ids)
    if unknown:
        raise SystemExit(f"--requeue for packages not in --pkgs: {sorted(unknown)}")
    both = set(requeue) & set(requeue_blocked)
    if both:
        raise SystemExit(f"package given both --requeue and --requeue-blocked: {sorted(both)}")
    if serial_group_limit < 1:
        raise SystemExit("--group-limit must be >= 1")
    packages: list[dict] = []
    held: dict[str, list[str]] = {}
    for pid in package_ids:
        pkg = program_lib.find_package(manifest, pid)
        if pkg["plane"] in ("external", "docs"):
            raise SystemExit(f"{pid} is {pkg['plane']}-plane; not launchable")
        for group in pkg.get("serial_groups", []):
            held.setdefault(group, []).append(pid)
            if len(held[group]) > serial_group_limit:
                raise SystemExit(f"serial group {group} held by {held[group]} exceeds --group-limit {serial_group_limit}")
        entry: dict = {"package_id": pid, "max_rounds": max_rounds, "start_round": 1, "prior": None}
        if pid in requeue:
            with open(requeue[pid], encoding="utf8") as fh:
                record = json.load(fh)
            if record.get("package_id") != pid:
                raise SystemExit(f"record {requeue[pid]} is for {record.get('package_id')}, not {pid}")
            if record.get("status") != "REQUEUE":
                raise SystemExit(f"{pid}: record status is {record.get('status')}; only REQUEUE records can be requeued")
            entry["prior"], entry["start_round"] = program_lib.prior_from_record(record)
        elif pid in requeue_blocked:
            # A BLOCKED_EXTERNAL package may only re-enter after the coordinator amended its manifest entry
            # (documented skips, serial-group grant, ...): the amendment must be visible as a manifest change.
            with open(requeue_blocked[pid], encoding="utf8") as fh:
                record = json.load(fh)
            if record.get("package_id") != pid:
                raise SystemExit(f"record {requeue_blocked[pid]} is for {record.get('package_id')}, not {pid}")
            if record.get("status") != "BLOCKED_EXTERNAL":
                raise SystemExit(f"{pid}: record status is {record.get('status')}; --requeue-blocked needs BLOCKED_EXTERNAL")
            if record.get("manifest_sha256") == manifest["manifest_sha256"]:
                raise SystemExit(f"{pid}: BLOCKED_EXTERNAL under the SAME manifest ({manifest['manifest_sha256'][:12]}); amend the manifest entry first")
            entry["prior"], entry["start_round"] = program_lib.prior_from_record(record)
        packages.append(entry)
    out_dir = os.path.join(ROOT, ".devin", "program", "runs")
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, f"WAVE__{base_sha[:12]}__{wave_id}.py")
    with open(path, "w", encoding="utf8") as fh:
        fh.write(
            TEMPLATE.format(
                lib_dir=HERE,
                wave_id=wave_id,
                base_sha=base_sha,
                integration_branch=integration_branch,
                manifest_path=MANIFEST,
                manifest_sha=manifest["manifest_sha256"],
                out_root=LEDGER_ROOT,
                mode=mode,
                serial_group_limit=serial_group_limit,
                packages=packages,
            )
        )
    return path


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("base_sha")
    ap.add_argument("wave_id")
    ap.add_argument("--pkgs", required=True, help="comma-separated package ids")
    ap.add_argument("--branch", default=INTEGRATION_BRANCH)
    ap.add_argument("--mode", default=None)
    ap.add_argument("--rounds", type=int, default=2)
    ap.add_argument("--group-limit", type=int, default=1, help="max packages per serial group in this wave (1 = exclusive); >1 records the frozen integration order and requeues conflicts")
    ap.add_argument("--requeue", action="append", default=[], metavar="PKG=RECORD_JSON")
    ap.add_argument("--requeue-blocked", action="append", default=[], metavar="PKG=RECORD_JSON", help="BLOCKED_EXTERNAL record whose manifest entry was amended since")
    a = ap.parse_args()
    rqb: dict[str, str] = {}
    for item in a.requeue_blocked:
        pid, _, path = item.partition("=")
        if not pid or not path:
            raise SystemExit(f"bad --requeue-blocked {item!r}")
        rqb[pid] = path
    rq: dict[str, str] = {}
    for item in a.requeue:
        pid, _, rec = item.partition("=")
        if not pid or not rec:
            raise SystemExit(f"--requeue expects PKG=RECORD_JSON, got {item!r}")
        rq[pid] = rec
    pkgs = [p.strip() for p in a.pkgs.split(",") if p.strip()]
    print(make(a.base_sha, a.wave_id, pkgs, integration_branch=a.branch, mode=a.mode, max_rounds=a.rounds, requeue=rq, requeue_blocked=rqb, serial_group_limit=a.group_limit))
