export { extractFrameStats, extractFrameStatsAsync } from "./frameStats.js";
export { DRILL_LIBRARY_V0_VERSION, FAULT_TAXONOMY_V0_DRAFT_VERSION } from "./coachReview.js";
export { checkArtifactInvariants, type InvariantViolation } from "./invariants.js";
export { runCorpusCheck, type CorpusCheckReport, type CorpusViolation } from "./corpusCheck.js";
export { checkProvenanceChain, PROVENANCE_CHAIN_VERSION } from "./provenanceChain.js";
export {
  BALL_CANDIDATE_GATE_VERSION,
  BALL_GATES,
  resolveBallModality,
  windowBallObservations,
  type BallCandidateDiagnostics,
  type TrajectoryFile,
} from "./ballCandidates.js";
export {
  aggregateBallOcclusionResults,
  BALL_BUCKET_ORDER,
  bucketForBallLabel,
  collectCommittedBallLabels,
  scoreBallOcclusionCase,
  type BallBucketScore,
  type BallGoldBucket,
  type BallOcclusionCaseResult,
  type BallOcclusionViolation,
} from "./ballOcclusionBench.js";
export {
  BALL_CONFIDENCE_MODEL,
  BALL_GATES2,
  BALL_TRACKER_VERSION,
  ballSpeedSeries,
  buildBallTracks,
  linkBallTimeline,
  selectPrimaryBallTrack,
  type BallAblation,
  type BallCandidateFile,
  type BallState,
  type BallTimeline,
  type BallTrackCandidate,
  type BallTrackingOutcome,
  type BallTrackObservation,
} from "./ballTracker.js";
export {
  buildPlayerTracks,
  otherPlayersWrists,
  PLAYER_TRACKER_VERSION,
  selectTargetPlayer,
  targetPoseSequence,
  type PeopleFile,
  type PlayerTrack,
  type TargetSelection,
} from "./playerTracker.js";
export {
  buildPaddleTracks,
  MERGE_LINK_GATES,
  OWNERSHIP_GUARD_GATES,
  OWNERSHIP_GUARD_VERSION,
  PADDLE_CONFIDENCE_MODEL,
  PADDLE_TRACKER_VERSION,
  mergePaddleTracklets,
  paddleSpeedSeries,
  selectPrimaryPaddleTrack,
  TRACKER_GATES,
  trackletLinkGate,
  trackletTail,
  wristSeries,
  type NormalizedBox,
  type PaddleSelectionOptions,
  type PaddleTrackCandidate,
  type PaddleTrackingOutcome,
  type RawPaddleDetectionFile,
  type PaddleDetectionSource,
  type TrackedPaddleObservation,
} from "./paddleTracker.js";
export {
  classifyMergeCandidate,
  enumerateMergeCandidatePairs,
  MERGE_SAFETY_GATES,
  MERGE_SAFETY_VERSION,
  sweepMergeCandidates,
  type BridgedFrame,
  type BridgedFrameProvenance,
  type MergeCandidatePair,
  type MergeCandidateSafetyReport,
  type MergeCheckStatus,
  type MergeSafetyCheck,
  type MergeSafetyContext,
  type MergeSafetySweepResult,
  type MergeSafetyVerdict,
} from "./paddleMergeSafety.js";
export {
  admitCropDetections,
  bridgeTrackedEstimates,
  CROP_RECOVERY_GATES,
  isFpFamily,
  mergeCropDetectionsIntoFile,
  PADDLE_CROP_RECOVERY_VERSION,
  paddleLostFrameTimes,
  planWristCropRects,
  type CropAdmissionResult,
  type CropDetectionFrame,
  type CropPlanFrame,
  type CropRect,
} from "./paddleCropRecovery.js";
export {
  DEFAULT_TWO_PASS_CONFIG,
  mergePaddleDetectionFiles,
  PADDLE_SCHEDULE_VERSION,
  planTwoPassSchedule,
  type DenseRegion,
  type TwoPassSchedule,
  type TwoPassScheduleConfig,
  type TwoPassScheduleInput,
} from "./paddleSchedule.js";
export {
  proposeStrokeEvents,
  selectTargetEvent,
  STROKE_EVENT_VERSION,
  type StrokeEventProposal,
  type TargetEventSelection,
} from "./strokeEvents.js";
export {
  PHASE_TEMPORAL_V2_VERSION,
  PHASE_TEMPORAL_VERSION,
  segmentPhasesTemporal,
  segmentPhasesTemporalV2,
  type TemporalPhaseOutcome,
} from "./phaseTemporal.js";
export { renderReport, type LabRunReport } from "./report.js";
export {
  classifyStroke,
  STROKE_HEURISTIC_VERSION,
  STROKE_TAXONOMY_V3,
  type StrokePrediction,
  type StrokeV3,
} from "./strokeHeuristic.js";
export {
  applyDeclaredIntentPrior,
  benchStrokeGold,
  compatibleTechniques,
  evaluatePrediction,
  formatConfusion,
  STROKE_GOLD_SCHEMA_VERSION,
  STROKE_GOLD_TAXONOMY_VERSION,
  V3_LEAF_FAMILY,
  validateStrokeGoldFile,
  type BenchReport,
  type BenchRow,
  type DeclaredIntentLike,
  type IntentPriorOutcome,
  type LevelVerdicts,
  type StrokeGoldFile,
  type StrokeGoldLabel,
  type StrokePredictionLike,
} from "./strokeTaxonomyBench.js";
export {
  buildStrokeSequence,
  KINETIC_MEASUREMENT_STATUS,
  SEQUENCE_SCHEMA_VERSION,
  type KineticEvent,
  type StrokeSequence,
} from "./strokeSequence.js";
export {
  COACH_QUALIFICATION_POLICY_VERSION,
  COACH_REGISTRY_SCHEMA_VERSION,
  isEligibleReviewer,
  KNOWN_QUALIFICATION_POLICY_VERSIONS,
  PROVISIONING_ACTION_SCHEMA_VERSION,
  provisioningActionIdFor,
  QUALIFICATION_CRITERIA_V1,
  QUALIFICATION_CRITERION_IDS,
  scaffoldCoachRegistryV2,
  validateCoachQualification,
  validateCoachRegistry,
  validateCoachRegistryEntry,
  validateProvisioningAction,
  type CertificationRecord,
  type CoachQualification,
  type CoachRegistryEntryV2,
  type CoachRegistryV2,
  type ProvisioningAction,
  type ProvisioningActionKind,
  type QualificationCriterionId,
  type VerificationMethod,
  type VerifiedClaim,
} from "./coachProvisioning.js";
export {
  buildFreshUserReport,
  CLAIM_TO_EVENT,
  countSilentFailures,
  independenceCoverage,
  ingestTrials,
  LABELABLE_CLAIMS,
  type FreshUserReport,
  type IndependenceCoverage,
  type LabelableClaim,
  type SilentFailureCounts,
  type TrialClaimLabel,
  type TrialIngestResult,
  type TrialLabel,
} from "./freshUserTrials.js";
