/**
 * mod-session-keeper × boundary-malformed — seeded stress campaign over the
 * REAL sessionKeeper.ts + sessionLifecycle.ts (nothing mocked in between; the
 * only injection points are the module's own `fetchFn` seam and jest fake
 * timers for AppState / setTimeout).
 *
 * Three families, one seed space (family = seed range, replayable with
 * STRESS_SEED=<n>):
 *
 *   A  refreshApiSession(): the server body is a GENERATED byte string served
 *      through a real `Response` — truncated / trailing-garbage / BOM /
 *      duplicate-key / prototype-pollution-key JSON, wrong types at every
 *      field, numeric edges (-0, NaN, ±Infinity, 1e999, 1e308, 2^53+1,
 *      ms-scale expiry), null bytes, 64 KiB and 1 MiB strings, path traversal,
 *      unicode normalization pairs, lone surrogates, empty arrays/objects,
 *      future schema versions, every HTTP status class, plus transport faults
 *      (rejecting fetch, synchronously throwing fetch, hang → 15 s abort) and
 *      non-compliant fetch results (null, no `json`, `json` throwing
 *      synchronously, `json` returning a non-promise).
 *   B  startSessionKeeper(): the same generated bodies scripted across a
 *      keeper run with generated inputs (64 KiB / null-byte / traversal
 *      refresh tokens, odd apiBaseUrl, bearerExpiresAtMs ∈ {null, NaN, ±∞,
 *      -0, past, 2^53, 1e308, at the lead boundaries}) and generated events
 *      (time advances, AppState strings incl. non-'active' junk, bursts of
 *      refreshSessionNow, restart, stop+refreshSessionNow).
 *   C  revokeApiSession(): malformed sessions × fetch faults.
 *
 * Oracle (independent of the implementation; violations are recorded per
 * seed with a code so a failure is replayable and minimizable):
 *   T  rejects only with SessionRefreshError (typed error, never a raw
 *      TypeError/SyntaxError out of the module)
 *   X  outcome equals the reference contract: 401/403 → revoked; 2xx with
 *      `session.{accessToken,refreshToken}` non-blank strings and a finite
 *      `expiresAt` → rotated with exactly those tokens; anything else →
 *      retryable
 *   F  a rotated `bearerExpiresAtMs` is a finite number
 *   U  exactly one POST to `${apiBaseUrl}/v1/auth/refresh` (or /logout) per
 *      call, with an AbortSignal and JSON headers
 *   R  the request body round-trips the refresh token byte-for-byte
 *   P  Object.prototype / Array.prototype gain no keys (pollution)
 *   I1–I6  keeper invariants as pinned by xcMatrixNetworkAuth2.keeper
 *          (revoke iff a 401/403 was delivered, at most once; silence after
 *          revoke; deferred for every settled non-refusal failure; token
 *          continuity; ≤1 in flight; onRotated == what the server issued)
 *   I7 no refresh storm: never more than 30 requests in any 60 s of quiet
 *      simulated time (the edge per-IP budget) — a kill switch stops the
 *      keeper at 200/60 s so a storm cannot stall the suite
 *   I8 callbacks of a superseded keeper generation never fire
 *   I9 junk AppState values (anything but exactly 'active') never trigger a
 *      refresh; stopSessionKeeper() → refreshSessionNow() sends nothing
 *
 * Run (apps/mobile):
 *   npx jest --ci __tests__/stress/sessionKeeperBoundaryMalformed.stress.test.ts
 *   STRESS_ITER=3200 npx jest --ci __tests__/stress/sessionKeeperBoundaryMalformed.stress.test.ts
 *   STRESS_SEED=1234 npx jest --ci __tests__/stress/sessionKeeperBoundaryMalformed.stress.test.ts
 * Artifact: artifacts/stress/mod-session-keeper/boundary-malformed-*.json
 * (STRESS_OUT overrides the directory).
 */
import { AppState } from 'react-native';
import {
  refreshSessionNow,
  retryDelayMs,
  startSessionKeeper,
  stopSessionKeeper,
} from '../../src/account/sessionKeeper';
import {
  refreshApiSession,
  revokeApiSession,
  SessionRefreshError,
  type RefreshedTokens,
} from '../../src/account/sessionLifecycle';

declare const require: (id: string) => unknown;
declare const __dirname: string;
declare const process: {
  env: Record<string, string | undefined>;
  version: string;
};
declare function setImmediate(cb: (value?: unknown) => void): unknown;
const fs = require('fs') as {
  mkdirSync: (p: string, options: { recursive: true }) => void;
  writeFileSync: (p: string, data: string) => void;
};
const path = require('path') as {
  join: (...parts: string[]) => string;
  resolve: (...parts: string[]) => string;
};

const REAL_NOW: () => number = Date.now.bind(Date);

// ─── Seeded PRNG ─────────────────────────────────────────────────────────────

function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
type Rng = () => number;
const pick = <T>(rng: Rng, items: readonly T[]): T =>
  items[Math.floor(rng() * items.length)]!;
const int = (rng: Rng, lo: number, hi: number) =>
  lo + Math.floor(rng() * (hi - lo + 1));

// ─── Generated JSON fragments ────────────────────────────────────────────────

/** A raw JSON fragment (may be syntactically invalid on purpose). */
interface Frag {
  raw: string;
  tag: string;
}

const jsonStr = (s: string): string => JSON.stringify(s);

function randomToken(rng: Rng, len: number): string {
  const alphabet =
    'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.';
  let s = '';
  for (let i = 0; i < len; i++) s += alphabet[int(rng, 0, alphabet.length - 1)];
  return s;
}

/** Fragments used in the token slots (accessToken / refreshToken). */
function tokenFrag(rng: Rng, seed: number): Frag {
  const r = rng();
  if (r < 0.55) {
    return {
      raw: jsonStr(randomToken(rng, int(rng, 1, 400))),
      tag: 'token:valid',
    };
  }
  const cases: Frag[] = [
    { raw: '""', tag: 'token:empty' },
    { raw: jsonStr('   '), tag: 'token:spaces' },
    { raw: jsonStr('\t\n\r '), tag: 'token:ascii-ws' },
    { raw: jsonStr('\u00a0\u2000\u3000\ufeff'), tag: 'token:unicode-ws' },
    { raw: jsonStr('\u200b'), tag: 'token:zero-width-space' },
    { raw: jsonStr('\u0000'), tag: 'token:nul' },
    { raw: jsonStr('tok\u0000en'), tag: 'token:embedded-nul' },
    { raw: jsonStr('tok\nen\r'), tag: 'token:crlf' },
    { raw: jsonStr('a'.repeat(65_536)), tag: 'token:64KiB' },
    { raw: jsonStr('a'.repeat(65_537)), tag: 'token:64KiB+1' },
    { raw: jsonStr('\u00e9'.repeat(65_536)), tag: 'token:64Ki-codepoints' },
    {
      raw: jsonStr('\u{1F468}\u200D\u{1F469}\u200D\u{1F467}'.repeat(4096)),
      tag: 'token:graphemes',
    },
    { raw: jsonStr('../../etc/passwd'), tag: 'token:traversal' },
    { raw: jsonStr('..%2F..%2Fetc%2Fpasswd'), tag: 'token:traversal-enc' },
    { raw: jsonStr('/v1/auth/logout'), tag: 'token:route' },
    { raw: jsonStr('caf\u00e9'), tag: 'token:nfc' },
    { raw: jsonStr('cafe\u0301'), tag: 'token:nfd' },
    { raw: jsonStr('\ud800'), tag: 'token:lone-surrogate' },
    { raw: '"\\ud800"', tag: 'token:lone-surrogate-escape' },
    { raw: jsonStr('<script>alert(1)</script>'), tag: 'token:html' },
    { raw: jsonStr("'; DROP TABLE shots; --"), tag: 'token:sql' },
    { raw: jsonStr('null'), tag: 'token:"null"' },
    { raw: jsonStr('undefined'), tag: 'token:"undefined"' },
    { raw: jsonStr('__proto__'), tag: 'token:"__proto__"' },
    { raw: jsonStr(`${seed}`), tag: 'token:numeric-string' },
    { raw: '0', tag: 'token:number-0' },
    { raw: '1', tag: 'token:number' },
    { raw: '-0', tag: 'token:-0' },
    { raw: '1e308', tag: 'token:1e308' },
    { raw: 'true', tag: 'token:true' },
    { raw: 'false', tag: 'token:false' },
    { raw: 'null', tag: 'token:null' },
    { raw: '[]', tag: 'token:[]' },
    { raw: '{}', tag: 'token:{}' },
    { raw: '["tok"]', tag: 'token:[str]' },
    { raw: '{"token":"tok"}', tag: 'token:{obj}' },
    { raw: '"\\x41"', tag: 'token:bad-escape' },
    { raw: '"tok\nen"', tag: 'token:raw-newline' },
    { raw: '"unterminated', tag: 'token:unterminated' },
    { raw: "'single'", tag: 'token:single-quotes' },
    { raw: 'undefined', tag: 'token:undefined-literal' },
    { raw: 'NaN', tag: 'token:NaN-literal' },
  ];
  if (seed % 97 === 0) {
    cases.push({ raw: jsonStr('b'.repeat(1 << 20)), tag: 'token:1MiB' });
  }
  return pick(rng, cases);
}

const NOW_S = () => Math.floor(Date.now() / 1000);

/** Fragments used in the expiresAt slot. */
function expiryFrag(rng: Rng): Frag {
  const r = rng();
  if (r < 0.45) {
    return { raw: String(NOW_S() + int(rng, 61, 86_400)), tag: 'exp:valid' };
  }
  const cases: Frag[] = [
    { raw: String(NOW_S() + 3600), tag: 'exp:1h' },
    { raw: String(NOW_S() - 5), tag: 'exp:past' },
    { raw: String(NOW_S() + 30), tag: 'exp:inside-lead' },
    { raw: String(NOW_S() + 60), tag: 'exp:at-lead' },
    { raw: String(NOW_S() + 7 * 86_400), tag: 'exp:7d' },
    { raw: String(NOW_S() + 25 * 86_400), tag: 'exp:25d(>2^31ms)' },
    { raw: String(Date.now() + 3_600_000), tag: 'exp:ms-scale' },
    { raw: `${NOW_S() + 3600}.999`, tag: 'exp:fraction' },
    { raw: '0', tag: 'exp:0' },
    { raw: '-0', tag: 'exp:-0' },
    { raw: '-1', tag: 'exp:-1' },
    { raw: '-9007199254740993', tag: 'exp:-2^53-1' },
    { raw: '9007199254740993', tag: 'exp:2^53+1' },
    { raw: '1e308', tag: 'exp:1e308' },
    { raw: '1.7976931348623157e308', tag: 'exp:MAX_VALUE' },
    { raw: '1e999', tag: 'exp:1e999(→Infinity)' },
    { raw: '-1e999', tag: 'exp:-1e999(→-Infinity)' },
    { raw: '5e-324', tag: 'exp:MIN_VALUE' },
    { raw: '1e-400', tag: 'exp:1e-400(→0)' },
    { raw: 'NaN', tag: 'exp:NaN-literal' },
    { raw: 'Infinity', tag: 'exp:Infinity-literal' },
    { raw: '-Infinity', tag: 'exp:-Infinity-literal' },
    { raw: '0x10', tag: 'exp:hex' },
    { raw: '01', tag: 'exp:leading-zero' },
    { raw: '.5', tag: 'exp:.5' },
    { raw: '5.', tag: 'exp:5.' },
    { raw: '1_000', tag: 'exp:underscore' },
    { raw: `"${NOW_S() + 3600}"`, tag: 'exp:string' },
    { raw: '"1e3"', tag: 'exp:"1e3"' },
    { raw: '""', tag: 'exp:""' },
    { raw: 'true', tag: 'exp:true' },
    { raw: 'null', tag: 'exp:null' },
    { raw: `[${NOW_S() + 3600}]`, tag: 'exp:[n]' },
    { raw: `{"seconds":${NOW_S() + 3600}}`, tag: 'exp:{obj}' },
    { raw: '[]', tag: 'exp:[]' },
    { raw: '{}', tag: 'exp:{}' },
    { raw: 'undefined', tag: 'exp:undefined-literal' },
  ];
  return pick(rng, cases);
}

/** Whole-body shapes. */
function bodyFrag(rng: Rng, seed: number): Frag {
  const a = tokenFrag(rng, seed);
  const r = tokenFrag(rng, seed);
  const e = expiryFrag(rng);
  const session = `{"accessToken":${a.raw},"refreshToken":${r.raw},"expiresAt":${e.raw}}`;
  const tags = [a.tag, r.tag, e.tag];
  const plain = (): Frag => ({
    raw: `{"session":${session}}`,
    tag: 'shape:plain',
  });
  const shapes: Array<() => Frag> = [
    plain,
    plain,
    plain,
    plain,
    plain,
    plain,
    () => ({
      raw: `{"schemaVersion":99,"session":${session},"future":{"x":[1,2,3]}}`,
      tag: 'shape:future-schema',
    }),
    () => ({
      raw: `{"__proto__":{"polluted${seed}":true},"session":${session}}`,
      tag: 'shape:__proto__-top',
    }),
    () => ({
      raw: `{"session":{"__proto__":{"polluted${seed}":true},"accessToken":${a.raw},"refreshToken":${r.raw},"expiresAt":${e.raw}}}`,
      tag: 'shape:__proto__-session',
    }),
    () => ({
      raw: `{"constructor":{"prototype":{"polluted${seed}":true}},"session":${session}}`,
      tag: 'shape:constructor.prototype',
    }),
    () => ({
      raw: `{"session":${session},"session":null}`,
      tag: 'shape:duplicate-session-null',
    }),
    () => ({
      raw: `{"session":null,"session":${session}}`,
      tag: 'shape:duplicate-session-last-wins',
    }),
    () => ({ raw: `{"session":[${session}]}`, tag: 'shape:session-array' }),
    () => ({ raw: `[${session}]`, tag: 'shape:top-array' }),
    () => ({ raw: `[]`, tag: 'shape:[]' }),
    () => ({ raw: `{}`, tag: 'shape:{}' }),
    () => ({ raw: `null`, tag: 'shape:null' }),
    () => ({ raw: `"session"`, tag: 'shape:string' }),
    () => ({ raw: `42`, tag: 'shape:number' }),
    () => ({ raw: ``, tag: 'shape:empty' }),
    () => ({ raw: ` \n\t `, tag: 'shape:whitespace' }),
    () => ({ raw: `\ufeff{"session":${session}}`, tag: 'shape:bom' }),
    () => ({ raw: `{"user":{"id":"x"}}`, tag: 'shape:no-session' }),
    () => ({ raw: `{"session":${session}}}`, tag: 'shape:trailing-brace' }),
    () => ({ raw: `{"session":${session}}xx`, tag: 'shape:trailing-garbage' }),
    () => ({ raw: `{"session":${session}}\u0000`, tag: 'shape:trailing-nul' }),
    () => ({ raw: `{"session":${session},}`, tag: 'shape:trailing-comma' }),
    () => ({ raw: `{session:${session}}`, tag: 'shape:unquoted-key' }),
    () => ({ raw: `{"session"=${session}}`, tag: 'shape:equals' }),
    () => ({
      raw: `// c\n{"session":${session}}`,
      tag: 'shape:comment',
    }),
    () => {
      const full = `{"session":${session}}`;
      const cut = int(rng, 0, Math.max(0, Math.min(full.length - 1, 400)));
      return { raw: full.slice(0, cut), tag: `shape:truncated@${cut}` };
    },
    () => ({
      raw: `{"pad":${jsonStr('p'.repeat(70_000))},"session":${session}}`,
      tag: 'shape:64KiB-pad',
    }),
    () => ({
      raw: `{"arr":[${'0,'.repeat(20_000)}0],"session":${session}}`,
      tag: 'shape:20k-array',
    }),
    () => {
      const depth = 500;
      return {
        raw: `${'{"a":'.repeat(depth)}{"session":${session}}${'}'.repeat(depth)}`,
        tag: 'shape:nested-500',
      };
    },
    () => ({
      raw: `{"session":${session},"extra":${jsonStr('\u0000'.repeat(100))}}`,
      tag: 'shape:extra-nul-field',
    }),
    () => ({
      raw: `{"Session":${session}}`,
      tag: 'shape:case-variant-key',
    }),
    () => ({
      raw: `{"session ":${session}}`,
      tag: 'shape:trailing-space-key',
    }),
    () => ({
      raw: `{"session":{"accessToken":${a.raw},"refreshToken":${r.raw}}}`,
      tag: 'shape:missing-expiresAt',
    }),
    () => ({
      raw: `{"session":{"access_token":${a.raw},"refresh_token":${r.raw},"expires_at":${e.raw}}}`,
      tag: 'shape:snake_case',
    }),
    () => ({
      raw: `{"session":{"accessToken":${a.raw},"refreshToken":${r.raw},"expiresAt":${e.raw},"expiresIn":3600,"tokenType":"bearer"}}`,
      tag: 'shape:extra-fields',
    }),
  ];
  const shape = pick(rng, shapes)();
  return { raw: shape.raw, tag: [shape.tag, ...tags].join('|') };
}

// ─── Served cases (what one request sees) ────────────────────────────────────

type Transport =
  | 'delivered'
  | 'net_error'
  | 'sync_throw'
  | 'hang'
  | 'resolve_null'
  | 'resolve_undefined'
  | 'duck_no_json'
  | 'duck_json_sync_throw'
  | 'duck_json_non_promise'
  | 'duck_status_string';

const STATUSES: readonly number[] = [
  200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
  200, 201, 202, 204, 205, 299, 300, 301, 304, 400, 401, 403, 404, 405, 408,
  409, 413, 418, 422, 429, 451, 500, 501, 502, 503, 504, 599,
];
const NULL_BODY_STATUSES = new Set([204, 205, 304]);

interface ServedCase {
  id: string;
  status: number;
  body: string | null;
  transport: Transport;
}

function servedCase(rng: Rng, seed: number, faultRate = 0.15): ServedCase {
  const r = rng();
  if (r < faultRate) {
    const transport = pick<Transport>(rng, [
      'net_error',
      'sync_throw',
      'hang',
      'resolve_null',
      'resolve_undefined',
      'duck_no_json',
      'duck_json_sync_throw',
      'duck_json_non_promise',
      'duck_status_string',
    ]);
    return { id: `transport:${transport}`, status: 200, body: null, transport };
  }
  const status = pick(rng, STATUSES);
  const body = bodyFrag(rng, seed);
  return {
    id: `status:${status}|${body.tag}`,
    status,
    body: NULL_BODY_STATUSES.has(status) ? null : body.raw,
    transport: 'delivered',
  };
}

// ─── Reference contract (the oracle) ─────────────────────────────────────────

type Kind = 'rotate' | 'revoke' | 'transient';
interface Expected {
  kind: Kind;
  tokens: RefreshedTokens | null;
}

/**
 * Mirrors the documented contract, NOT the implementation: 401/403 refuse;
 * any 2xx whose body is JSON with `session.accessToken` / `refreshToken`
 * non-blank strings and a finite numeric `expiresAt` rotates; everything
 * else is transient. `Response.json()` decodes UTF-8 with BOM stripping, so
 * a leading BOM is stripped here too (tagged `shape:bom` for the record).
 */
function referenceOutcome(status: number, body: string | null): Expected {
  if (status === 401 || status === 403) return { kind: 'revoke', tokens: null };
  if (!(status >= 200 && status < 300))
    return { kind: 'transient', tokens: null };
  let parsed: unknown;
  try {
    parsed = JSON.parse((body ?? '').replace(/^\ufeff/, ''));
  } catch {
    return { kind: 'transient', tokens: null };
  }
  if (parsed === null || typeof parsed !== 'object')
    return { kind: 'transient', tokens: null };
  const session = (parsed as { session?: unknown }).session;
  if (session === null || typeof session !== 'object')
    return { kind: 'transient', tokens: null };
  const s = session as {
    accessToken?: unknown;
    refreshToken?: unknown;
    expiresAt?: unknown;
  };
  if (
    typeof s.accessToken !== 'string' ||
    s.accessToken.trim() === '' ||
    typeof s.refreshToken !== 'string' ||
    s.refreshToken.trim() === '' ||
    typeof s.expiresAt !== 'number' ||
    !Number.isFinite(s.expiresAt)
  ) {
    return { kind: 'transient', tokens: null };
  }
  return {
    kind: 'rotate',
    tokens: {
      bearerToken: s.accessToken,
      refreshToken: s.refreshToken,
      bearerExpiresAtMs: s.expiresAt * 1000,
    },
  };
}

/** What the reference says a transport fault must do (contract: SessionRefreshError, retryable). */
function expectedFor(c: ServedCase): Expected {
  if (c.transport !== 'delivered') return { kind: 'transient', tokens: null };
  return referenceOutcome(c.status, c.body);
}

// ─── Fetch emulation ─────────────────────────────────────────────────────────

function abortError(): Error {
  const error = new Error('Aborted');
  error.name = 'AbortError';
  return error;
}

interface Call {
  url: string;
  init: RequestInit | undefined;
}

/** Builds a fetchFn serving `c`; records every call into `calls`. */
function fetchFor(c: ServedCase, calls: Call[]) {
  return (url: string, init?: RequestInit): Promise<Response> => {
    calls.push({ url, init });
    switch (c.transport) {
      case 'sync_throw':
        throw new TypeError('Network request failed (sync)');
      case 'net_error':
        return Promise.reject(new TypeError('Network request failed'));
      case 'hang':
        return new Promise<never>((_, reject) => {
          const signal = init?.signal;
          if (signal?.aborted) reject(abortError());
          signal?.addEventListener('abort', () => reject(abortError()));
        });
      case 'resolve_null':
        return Promise.resolve(null as unknown as Response);
      case 'resolve_undefined':
        return Promise.resolve(undefined as unknown as Response);
      case 'duck_no_json':
        return Promise.resolve({
          ok: true,
          status: 200,
        } as unknown as Response);
      case 'duck_json_sync_throw':
        return Promise.resolve({
          ok: true,
          status: 200,
          json: () => {
            throw new TypeError('body stream already read');
          },
        } as unknown as Response);
      case 'duck_json_non_promise':
        return Promise.resolve({
          ok: true,
          status: 200,
          json: () => ({ session: {} }),
        } as unknown as Response);
      case 'duck_status_string':
        return Promise.resolve({
          ok: false,
          status: '500',
          json: () => Promise.resolve({}),
        } as unknown as Response);
      case 'delivered':
        return Promise.resolve(
          new Response(c.body, {
            status: c.status,
            headers: { 'content-type': 'application/json' },
          }),
        );
    }
  };
}

// ─── Prototype-pollution sentinel ────────────────────────────────────────────

const OBJ_PROTO_KEYS = new Set(Object.getOwnPropertyNames(Object.prototype));
const ARR_PROTO_KEYS = new Set(Object.getOwnPropertyNames(Array.prototype));

function pollutionViolations(): string[] {
  const out: string[] = [];
  for (const k of Object.getOwnPropertyNames(Object.prototype))
    if (!OBJ_PROTO_KEYS.has(k)) out.push(`P Object.prototype gained ${k}`);
  for (const k of Object.getOwnPropertyNames(Array.prototype))
    if (!ARR_PROTO_KEYS.has(k)) out.push(`P Array.prototype gained ${k}`);
  const probe: Record<string, unknown> = {};
  for (const k of Object.keys(probe)) out.push(`P fresh object has key ${k}`);
  return out;
}

// ─── Result table ────────────────────────────────────────────────────────────

type Family = 'A:refreshApiSession' | 'B:sessionKeeper' | 'C:revokeApiSession';

interface SeedRow {
  seed: number;
  family: Family;
  id: string;
  expected: string;
  observed: string;
  verdict: 'HELD' | 'BROKEN';
  violations: string[];
}

/** Same violation repeated N times → one line with `×N`. */
function collapse(violations: string[]): string[] {
  const counts = new Map<string, number>();
  for (const v of violations) counts.set(v, (counts.get(v) ?? 0) + 1);
  return [...counts].map(([v, n]) => (n > 1 ? `${v} ×${n}` : v));
}

// ─── Family A ────────────────────────────────────────────────────────────────

const API = 'https://api.example.test';

function inputTokenFor(rng: Rng, seed: number): { value: string; tag: string } {
  const cases = [
    { value: randomToken(rng, 64), tag: 'in:valid' },
    { value: '', tag: 'in:empty' },
    { value: ' ', tag: 'in:space' },
    { value: '\u0000', tag: 'in:nul' },
    { value: 'r\u0000t', tag: 'in:embedded-nul' },
    { value: 'r\r\nt', tag: 'in:crlf' },
    { value: 'x'.repeat(65_536), tag: 'in:64KiB' },
    { value: '../../etc/passwd', tag: 'in:traversal' },
    { value: 'caf\u00e9', tag: 'in:nfc' },
    { value: 'cafe\u0301', tag: 'in:nfd' },
    { value: '\ud800', tag: 'in:lone-surrogate' },
    { value: '\u{1F468}\u200D\u{1F469}', tag: 'in:zwj' },
    { value: '"quoted"\\slash', tag: 'in:quotes' },
    { value: '{"refreshToken":"nested"}', tag: 'in:json-in-token' },
    { value: `${seed}`, tag: 'in:numeric-string' },
  ];
  return pick(rng, cases);
}

function apiBaseUrlFor(rng: Rng): { value: string; tag: string } {
  return pick(rng, [
    { value: API, tag: 'url:plain' },
    { value: `${API}/`, tag: 'url:trailing-slash' },
    { value: `${API}/../..`, tag: 'url:traversal' },
    { value: `${API}:443`, tag: 'url:port' },
    { value: 'http://127.0.0.1:54321/functions/v1/api', tag: 'url:local' },
    { value: '', tag: 'url:empty' },
    { value: 'https://\u00e9xample.test', tag: 'url:unicode-host' },
    { value: `${API}/v1/auth/refresh`, tag: 'url:already-route' },
    { value: `${API}?x=1`, tag: 'url:query' },
    { value: `${API}#frag`, tag: 'url:fragment' },
    { value: `${API}\u0000`, tag: 'url:nul' },
  ]);
}

async function runFamilyA(seed: number): Promise<SeedRow> {
  const rng = mulberry32(seed);
  const c = servedCase(rng, seed);
  const token = inputTokenFor(rng, seed);
  const base = apiBaseUrlFor(rng);
  const calls: Call[] = [];
  const violations: string[] = [];
  const expected = expectedFor(c);
  let observed = '';

  const pending = refreshApiSession(
    { apiBaseUrl: base.value, refreshToken: token.value },
    { fetchFn: fetchFor(c, calls) },
  );
  // Swallow so a late rejection never surfaces as unhandled; the outcome is
  // read below.
  pending.catch(() => undefined);
  if (c.transport === 'hang') {
    await jest.advanceTimersByTimeAsync(14_999);
    if (calls[0]?.init?.signal?.aborted)
      violations.push('U hang aborted before the 15 s budget');
    await jest.advanceTimersByTimeAsync(1);
  }
  let result: RefreshedTokens | null = null;
  let error: unknown = null;
  try {
    result = await pending;
  } catch (e) {
    error = e;
  }

  // U / R
  if (calls.length !== 1) violations.push(`U fetch called ${calls.length}×`);
  const call = calls[0];
  if (call) {
    if (call.url !== `${base.value}/v1/auth/refresh`)
      violations.push(`U url ${JSON.stringify(call.url)}`);
    if (call.init?.method !== 'POST') violations.push('U method not POST');
    if (!(call.init?.signal instanceof AbortSignal))
      violations.push('U no AbortSignal');
    const headers = call.init?.headers as Record<string, string> | undefined;
    if (headers?.['Content-Type'] !== 'application/json')
      violations.push('U content-type');
    if (headers?.Accept !== 'application/json') violations.push('U accept');
    try {
      const sent = JSON.parse(String(call.init?.body)) as {
        refreshToken?: unknown;
      };
      if (sent.refreshToken !== token.value)
        violations.push('R refresh token did not round-trip');
      if (Object.keys(sent).length !== 1)
        violations.push('R body carries extra fields');
    } catch {
      violations.push('R body not JSON');
    }
    if (c.transport === 'hang' && !call.init?.signal?.aborted)
      violations.push('U hang not aborted at 15 s');
  }

  // T / X / F
  if (result) {
    observed = 'rotate';
    if (expected.kind !== 'rotate') {
      violations.push(`X rotated but reference says ${expected.kind}`);
    } else if (
      result.bearerToken !== expected.tokens!.bearerToken ||
      result.refreshToken !== expected.tokens!.refreshToken ||
      !Object.is(result.bearerExpiresAtMs, expected.tokens!.bearerExpiresAtMs)
    ) {
      violations.push('X rotated tokens differ from the served session');
    }
    if (!Number.isFinite(result.bearerExpiresAtMs))
      violations.push(`F bearerExpiresAtMs=${result.bearerExpiresAtMs}`);
  } else if (error instanceof SessionRefreshError) {
    observed = error.retryable ? 'transient' : 'revoke';
    if (observed !== expected.kind)
      violations.push(`X ${observed} but reference says ${expected.kind}`);
    if (error.name !== 'SessionRefreshError') violations.push('T error.name');
  } else {
    const name =
      error instanceof Error
        ? `${error.name}: ${error.message}`
        : String(error);
    observed = `untyped-throw(${name})`;
    violations.push(`T non-SessionRefreshError escaped: ${name}`);
  }
  violations.push(...pollutionViolations());

  return {
    seed,
    family: 'A:refreshApiSession',
    id: `${c.id}|${token.tag}|${base.tag}`,
    expected: expected.kind,
    observed,
    verdict: violations.length ? 'BROKEN' : 'HELD',
    violations: collapse(violations),
  };
}

// ─── Family B ────────────────────────────────────────────────────────────────

type AppEvent =
  | { kind: 'advance'; ms: number }
  | { kind: 'appstate'; state: string }
  | { kind: 'refresh_now'; burst: number }
  | { kind: 'restart' }
  | { kind: 'stop_then_refresh_now' };

const APP_STATES = [
  'active',
  'active',
  'active',
  'background',
  'inactive',
  'unknown',
  'extension',
  '',
  'ACTIVE',
  'active ',
  'active\u0000',
  'Active',
];

function bearerExpiryFor(rng: Rng): { value: number | null; tag: string } {
  const now = Date.now();
  return pick(rng, [
    { value: null, tag: 'bexp:null' },
    { value: Number.NaN, tag: 'bexp:NaN' },
    { value: Number.POSITIVE_INFINITY, tag: 'bexp:+Inf' },
    { value: Number.NEGATIVE_INFINITY, tag: 'bexp:-Inf' },
    { value: -0, tag: 'bexp:-0' },
    { value: 0, tag: 'bexp:0' },
    { value: now - 1, tag: 'bexp:past' },
    { value: now, tag: 'bexp:now' },
    { value: now + 59_999, tag: 'bexp:lead-1' },
    { value: now + 60_000, tag: 'bexp:lead' },
    { value: now + 60_001, tag: 'bexp:lead+1' },
    { value: now + 5 * 60_000 - 1, tag: 'bexp:fg-lead-1' },
    { value: now + 5 * 60_000, tag: 'bexp:fg-lead' },
    { value: now + 3_600_000, tag: 'bexp:1h' },
    { value: now + 30 * 86_400_000, tag: 'bexp:30d(>2^31ms)' },
    { value: 2 ** 53, tag: 'bexp:2^53' },
    { value: 1e308, tag: 'bexp:1e308' },
    { value: Number.MIN_VALUE, tag: 'bexp:MIN_VALUE' },
  ]);
}

interface KeeperScenario {
  seed: number;
  refreshToken: { value: string; tag: string };
  apiBaseUrl: { value: string; tag: string };
  bearerExpiresAtMs: { value: number | null; tag: string };
  script: ServedCase[];
  events: AppEvent[];
}

function buildKeeperScenario(seed: number): KeeperScenario {
  const rng = mulberry32(seed);
  const scriptLength = int(rng, 3, 12);
  const script: ServedCase[] = [];
  for (let i = 0; i < scriptLength; i++)
    script.push(servedCase(rng, seed, 0.2));
  const eventCount = int(rng, 4, 16);
  const events: AppEvent[] = [];
  for (let i = 0; i < eventCount; i++) {
    const r = rng();
    if (r < 0.55) {
      events.push({
        kind: 'advance',
        ms: pick(rng, [
          1,
          999,
          1_000,
          4_999,
          5_000,
          15_000,
          29_999,
          30_000,
          59_999,
          60_000,
          5 * 60_000,
          3_600_000,
        ]),
      });
    } else if (r < 0.75) {
      events.push({ kind: 'appstate', state: pick(rng, APP_STATES) });
    } else if (r < 0.9) {
      events.push({ kind: 'refresh_now', burst: pick(rng, [1, 2, 5, 50]) });
    } else if (r < 0.95) {
      events.push({ kind: 'restart' });
    } else {
      events.push({ kind: 'stop_then_refresh_now' });
    }
  }
  return {
    seed,
    refreshToken: inputTokenFor(rng, seed),
    apiBaseUrl: apiBaseUrlFor(rng),
    bearerExpiresAtMs: bearerExpiryFor(rng),
    script,
    events,
  };
}

let appStateHandler: ((state: string) => void) | null = null;

interface Attempt {
  t: number;
  gen: number;
  served: string;
  expected: Kind;
  settled: boolean;
  /** settled while its generation was still the live keeper */
  settledLive: boolean;
}

const STORM_KILL_PER_60S = 200;
const STORM_LIMIT_PER_60S = 30;

function maxInAnyWindow(times: number[], windowMs: number): number {
  let best = 0;
  for (let i = 0, j = 0; i < times.length; i++) {
    while ((times[j] ?? Infinity) <= (times[i] ?? 0) - windowMs) j += 1;
    best = Math.max(best, i - j + 1);
  }
  return best;
}

async function runFamilyB(seed: number): Promise<SeedRow> {
  const sc = buildKeeperScenario(seed);
  const violations: string[] = [];
  const log: Attempt[] = [];
  const start = Date.now();
  let scriptIndex = 0;
  const inflightByGen = new Map<number, number>();
  let generation = 0;
  let liveGeneration = 0;
  let stopped = false;
  let currentToken = sc.refreshToken.value;
  let lastIssued: RefreshedTokens | null = null;
  let refusalsDelivered = 0;
  let revoked = 0;
  let deferred = 0;
  let rotated = 0;
  let killed = false;
  const times: number[] = [];

  const start_ = (token: string) => {
    generation += 1;
    const myGen = generation;
    liveGeneration = myGen;
    stopped = false;
    const fetchFn = async (url: string, init?: RequestInit) => {
      const t = Date.now() - start;
      times.push(t);
      const c = sc.script[scriptIndex % sc.script.length]!;
      scriptIndex += 1;
      const attempt: Attempt = {
        t,
        gen: myGen,
        served: c.id,
        expected: expectedFor(c).kind,
        settled: false,
        settledLive: false,
      };
      log.push(attempt);
      if (myGen !== liveGeneration)
        violations.push(`I8 request from superseded generation at t=${t}`);
      if (stopped)
        violations.push(`I9 request after stopSessionKeeper at t=${t}`);
      if (url !== `${sc.apiBaseUrl.value}/v1/auth/refresh`)
        violations.push(`U url ${JSON.stringify(url)}`);
      if ((inflightByGen.get(myGen) ?? 0) > 0)
        violations.push(`I5 concurrent refresh at t=${t}`);
      if (revoked > 0) violations.push(`I2 request after revocation at t=${t}`);
      let sent: unknown;
      try {
        sent = (JSON.parse(String(init?.body)) as { refreshToken?: unknown })
          .refreshToken;
      } catch {
        violations.push('R body not JSON');
      }
      if (sent !== currentToken)
        violations.push(`I4 stale/other refresh token sent at t=${t}`);
      if (!killed && maxInAnyWindow(times, 60_000) > STORM_KILL_PER_60S) {
        killed = true;
        violations.push(
          `I7 refresh storm: >${STORM_KILL_PER_60S} requests in 60 s (killed) at t=${t}`,
        );
        stopSessionKeeper();
        stopped = true;
        liveGeneration = -1;
      }
      inflightByGen.set(myGen, (inflightByGen.get(myGen) ?? 0) + 1);
      try {
        const calls: Call[] = [];
        const response = await fetchFor(c, calls)(url, init);
        if (c.transport === 'delivered' && myGen === liveGeneration) {
          const ref = referenceOutcome(c.status, c.body);
          if (ref.kind === 'revoke') refusalsDelivered += 1;
          if (ref.tokens) {
            lastIssued = ref.tokens;
            currentToken = ref.tokens.refreshToken;
          }
        }
        return response;
      } finally {
        attempt.settled = true;
        attempt.settledLive = myGen === liveGeneration;
        inflightByGen.set(myGen, (inflightByGen.get(myGen) ?? 0) - 1);
      }
    };
    startSessionKeeper({
      apiBaseUrl: sc.apiBaseUrl.value,
      refreshToken: token,
      bearerExpiresAtMs: sc.bearerExpiresAtMs.value,
      fetchFn,
      onRotated: tokens => {
        rotated += 1;
        if (myGen !== liveGeneration)
          violations.push('I8 onRotated from superseded generation');
        if (
          !lastIssued ||
          tokens.bearerToken !== lastIssued.bearerToken ||
          tokens.refreshToken !== lastIssued.refreshToken ||
          !Object.is(tokens.bearerExpiresAtMs, lastIssued.bearerExpiresAtMs)
        ) {
          violations.push('I6 onRotated tokens differ from what was served');
        }
        if (!Number.isFinite(tokens.bearerExpiresAtMs))
          violations.push(
            `F onRotated bearerExpiresAtMs=${tokens.bearerExpiresAtMs}`,
          );
      },
      onRevoked: () => {
        revoked += 1;
        if (myGen !== liveGeneration)
          violations.push('I8 onRevoked from superseded generation');
      },
      onDeferred: () => {
        deferred += 1;
        if (myGen !== liveGeneration)
          violations.push('I8 onDeferred from superseded generation');
      },
    });
  };

  start_(currentToken);
  let junkStateRequests = 0;
  for (const ev of sc.events) {
    if (killed) break;
    switch (ev.kind) {
      case 'advance':
        await jest.advanceTimersByTimeAsync(ev.ms);
        break;
      case 'appstate': {
        // refresh() reaches fetchFn synchronously (no await precedes the
        // fetch call), so a request caused by the event is visible right
        // away — before any due timer gets a chance to run.
        const before = log.length;
        appStateHandler?.(ev.state);
        if (ev.state !== 'active' && log.length !== before) {
          junkStateRequests += 1;
          violations.push(
            `I9 AppState ${JSON.stringify(ev.state)} triggered a refresh`,
          );
        }
        await jest.advanceTimersByTimeAsync(0);
        break;
      }
      case 'refresh_now':
        for (let i = 0; i < ev.burst; i++) refreshSessionNow();
        await jest.advanceTimersByTimeAsync(0);
        break;
      case 'restart': {
        // Starting again supersedes the running keeper; the new one gets a
        // fresh token identity so continuity is checked per generation.
        currentToken = `${sc.refreshToken.value}#restart${generation}`;
        lastIssued = null;
        // Revocation belongs to the old generation; the new one starts clean.
        revoked = 0;
        refusalsDelivered = 0;
        start_(currentToken);
        await jest.advanceTimersByTimeAsync(0);
        break;
      }
      case 'stop_then_refresh_now': {
        stopSessionKeeper();
        stopped = true;
        liveGeneration = -1;
        const before = log.length;
        refreshSessionNow();
        appStateHandler?.('active');
        await jest.advanceTimersByTimeAsync(0);
        if (log.length !== before)
          violations.push('I9 request after stopSessionKeeper()');
        // Bring a keeper back so the scenario keeps exercising the module.
        currentToken = `${sc.refreshToken.value}#restart${generation}`;
        lastIssued = null;
        revoked = 0;
        refusalsDelivered = 0;
        start_(currentToken);
        await jest.advanceTimersByTimeAsync(0);
        break;
      }
    }
  }

  // Quiet drain: hang timeout + max backoff + a bearer lifetime; the keeper
  // must still be alive (unless revoked) and must not storm.
  const drainFrom = log.length;
  const drainStartT = Date.now() - start;
  const DRAIN_MS = 15_000 + retryDelayMs(99) + 3_600_000 + 1_000;
  // When must the live keeper speak again? Derived from the reference
  // contract, not from the implementation.
  let nextRequestDueBy: number | null = null;
  if (revoked === 0 && !killed) {
    const last = [...log].reverse().find(a => a.gen === liveGeneration);
    if (!last) {
      const b = sc.bearerExpiresAtMs.value;
      nextRequestDueBy =
        b === null ? 0 : Math.max(b - start - 60_000, drainStartT + 1_000);
    } else if (!last.settled) {
      nextRequestDueBy = last.t + 15_000 + retryDelayMs(99) + 1_000;
    } else if (last.expected === 'transient') {
      nextRequestDueBy = last.t + retryDelayMs(99) + 1_000;
    } else {
      // Assigned only inside fetchFn, which narrowing cannot see.
      const issued = lastIssued as RefreshedTokens | null;
      if (issued) {
        nextRequestDueBy = Math.max(
          issued.bearerExpiresAtMs - start - 60_000,
          last.t + 30_000,
        );
      }
    }
  }
  if (!killed) await jest.advanceTimersByTimeAsync(DRAIN_MS);
  const drainTimes = times.filter(t => t >= drainStartT);
  const drainMax60 = maxInAnyWindow(drainTimes, 60_000);
  if (drainMax60 > STORM_LIMIT_PER_60S)
    violations.push(`I7 ${drainMax60} requests in 60 s of quiet time`);

  // I1
  if (revoked > 1) violations.push(`I1 onRevoked ${revoked}×`);
  if (refusalsDelivered > 0 && revoked === 0)
    violations.push('I1 refusal delivered but onRevoked never fired');
  if (refusalsDelivered === 0 && revoked > 0)
    violations.push('I1 onRevoked without a delivered 401/403');
  // I3 — deferred count vs settled non-refusal failures of the LIVE generation
  const settledFailures = log.filter(
    a => a.settledLive && a.expected === 'transient',
  ).length;
  if (!killed && deferred !== settledFailures) {
    violations.push(
      `I3 onDeferred ${deferred} != settled transient failures ${settledFailures}`,
    );
  }
  if (
    nextRequestDueBy !== null &&
    nextRequestDueBy <= drainStartT + DRAIN_MS &&
    log.length === drainFrom
  ) {
    violations.push(
      `I3 keeper went silent: a request was due by t=${nextRequestDueBy} but none arrived through t=${drainStartT + DRAIN_MS}`,
    );
  }

  violations.push(...pollutionViolations());
  stopSessionKeeper();

  return {
    seed,
    family: 'B:sessionKeeper',
    id: `${sc.refreshToken.tag}|${sc.apiBaseUrl.tag}|${sc.bearerExpiresAtMs.tag}|script[${sc.script.map(s => s.id).join(' ; ')}]|events=${sc.events.length}`,
    expected: 'I1-I9 hold',
    observed: `attempts=${log.length} rotated=${rotated} revoked=${revoked} deferred=${deferred} drainMax60s=${drainMax60} junkStateRequests=${junkStateRequests}`,
    verdict: violations.length ? 'BROKEN' : 'HELD',
    violations: collapse(violations),
  };
}

// ─── Family C ────────────────────────────────────────────────────────────────

async function runFamilyC(seed: number): Promise<SeedRow> {
  const rng = mulberry32(seed);
  const c = servedCase(rng, seed, 0.4);
  const bearer = inputTokenFor(rng, seed);
  const base = apiBaseUrlFor(rng);
  const calls: Call[] = [];
  const violations: string[] = [];
  const pending = revokeApiSession(
    {
      apiBaseUrl: base.value,
      bearerToken: bearer.value,
      canonicalAppUserId: `user-${seed}`,
      provider: 'apple',
      refreshToken: 'unused',
    },
    fetchFor(c, calls),
  );
  pending.catch(() => undefined);
  if (c.transport === 'hang') await jest.advanceTimersByTimeAsync(15_000);
  let observed = 'resolved';
  try {
    await pending;
  } catch (e) {
    observed = `rejected(${e instanceof Error ? e.name : String(e)})`;
    violations.push(`T revokeApiSession rejected: ${observed}`);
  }
  if (calls.length !== 1) violations.push(`U fetch called ${calls.length}×`);
  const call = calls[0];
  if (call) {
    if (call.url !== `${base.value}/v1/auth/logout`)
      violations.push(`U url ${JSON.stringify(call.url)}`);
    if (call.init?.method !== 'POST') violations.push('U method not POST');
    const headers = call.init?.headers as Record<string, string> | undefined;
    if (headers?.Authorization !== `Bearer ${bearer.value}`)
      violations.push(
        'R Authorization header does not carry the bearer verbatim',
      );
    if (call.init?.body !== undefined)
      violations.push('R logout carries a body');
    if (c.transport === 'hang' && !call.init?.signal?.aborted)
      violations.push('U hang not aborted at 15 s');
  }
  violations.push(...pollutionViolations());
  return {
    seed,
    family: 'C:revokeApiSession',
    id: `${c.id}|${bearer.tag}|${base.tag}`,
    expected: 'resolves, one POST /v1/auth/logout',
    observed,
    verdict: violations.length ? 'BROKEN' : 'HELD',
    violations: collapse(violations),
  };
}

// ─── Campaign ────────────────────────────────────────────────────────────────

const ITER = Number(process.env.STRESS_ITER ?? 400);
const ONLY = process.env.STRESS_SEED ? Number(process.env.STRESS_SEED) : null;
/** 60 % A / 25 % B / 15 % C, a function of the seed alone so that
 *  `STRESS_SEED=n` replays exactly what the campaign ran for seed n regardless
 *  of STRESS_ITER. */
function familyOf(seed: number): Family {
  const slot = seed % 20;
  if (slot < 12) return 'A:refreshApiSession';
  if (slot < 17) return 'B:sessionKeeper';
  return 'C:revokeApiSession';
}

async function runSeed(seed: number): Promise<SeedRow> {
  switch (familyOf(seed)) {
    case 'A:refreshApiSession':
      return runFamilyA(seed);
    case 'B:sessionKeeper':
      return runFamilyB(seed);
    case 'C:revokeApiSession':
      return runFamilyC(seed);
  }
}

const OUT_DIR =
  process.env.STRESS_OUT ??
  path.resolve(__dirname, '../../../../artifacts/stress/mod-session-keeper');

function installAppStateSpy(): void {
  appStateHandler = null;
  jest.spyOn(AppState, 'addEventListener').mockImplementation(((
    _type: string,
    handler: (state: string) => void,
  ) => {
    appStateHandler = handler;
    return {
      remove: () => {
        if (appStateHandler === handler) appStateHandler = null;
      },
    };
  }) as unknown as typeof AppState.addEventListener);
}

beforeEach(() => {
  jest.useFakeTimers();
  jest.setSystemTime(new Date('2026-09-06T12:00:00Z'));
  installAppStateSpy();
});

afterEach(() => {
  stopSessionKeeper();
  jest.useRealTimers();
  jest.restoreAllMocks();
});

describe('mod-session-keeper × boundary-malformed (seeded, replay with STRESS_SEED=<n>)', () => {
  it(`holds the refresh contract across ${ONLY === null ? ITER : 1} generated inputs`, async () => {
    const seeds =
      ONLY !== null ? [ONLY] : Array.from({ length: ITER }, (_, i) => i);
    const wallStart = REAL_NOW();
    const rows: SeedRow[] = [];
    for (const seed of seeds) {
      rows.push(await runSeed(seed));
    }
    const wallMs = REAL_NOW() - wallStart;
    const broken = rows.filter(r => r.verdict === 'BROKEN');

    const byFamily: Record<
      Family,
      { seeds: number; held: number; broken: number }
    > = {
      'A:refreshApiSession': { seeds: 0, held: 0, broken: 0 },
      'B:sessionKeeper': { seeds: 0, held: 0, broken: 0 },
      'C:revokeApiSession': { seeds: 0, held: 0, broken: 0 },
    };
    const expectedKinds: Record<string, number> = {};
    const tagCounts: Record<string, number> = {};
    const violationCodes: Record<string, number> = {};
    for (const r of rows) {
      const f = byFamily[r.family];
      f.seeds += 1;
      f[r.verdict === 'HELD' ? 'held' : 'broken'] += 1;
      expectedKinds[r.expected] = (expectedKinds[r.expected] ?? 0) + 1;
      for (const tag of r.id.split(/[|;[\]]/)) {
        const key = tag.trim().replace(/@\d+$/, '@n');
        if (key) tagCounts[key] = (tagCounts[key] ?? 0) + 1;
      }
      for (const v of r.violations) {
        const code = v.split(' ')[0] ?? '?';
        violationCodes[code] = (violationCodes[code] ?? 0) + 1;
      }
    }

    fs.mkdirSync(OUT_DIR, { recursive: true });
    const stamp = new Date(REAL_NOW()).toISOString().replace(/[:.]/g, '-');
    const report = {
      unit: 'mod-session-keeper',
      lens: 'boundary-malformed',
      plane:
        'mobile (jest, real sessionKeeper + sessionLifecycle, generated Response bodies, fake timers)',
      commit: process.env.STRESS_COMMIT ?? null,
      generatedAt: new Date(REAL_NOW()).toISOString(),
      node: process.version,
      config: {
        STRESS_ITER: ITER,
        familyOf: 'seed % 20: 0-11 → A, 12-16 → B, 17-19 → C',
      },
      replay:
        'STRESS_SEED=<seed> npx jest --ci __tests__/stress/sessionKeeperBoundaryMalformed.stress.test.ts',
      wallMs,
      totals: {
        executed: rows.length,
        held: rows.length - broken.length,
        broken: broken.length,
      },
      byFamily,
      expectedKinds,
      violationCodes,
      tagCounts,
      broken: broken.map(r => ({
        seed: r.seed,
        family: r.family,
        replay: `STRESS_SEED=${r.seed} npx jest --ci __tests__/stress/sessionKeeperBoundaryMalformed.stress.test.ts`,
        id: r.id,
        expected: r.expected,
        observed: r.observed,
        violations: r.violations,
      })),
      seeds: rows,
    };
    const file = path.join(OUT_DIR, `boundary-malformed-${stamp}.json`);
    fs.writeFileSync(file, JSON.stringify(report, null, 2));
    fs.writeFileSync(
      path.join(OUT_DIR, 'boundary-malformed-latest.json'),
      JSON.stringify(report, null, 2),
    );
    console.log(
      `[stress mod-session-keeper/boundary-malformed] ${rows.length} inputs, ${broken.length} broken, wall ${wallMs} ms → ${file}`,
    );

    if (ONLY === null) {
      // The campaign must actually have exercised every outcome class.
      expect(expectedKinds.rotate ?? 0).toBeGreaterThan(0);
      expect(expectedKinds.revoke ?? 0).toBeGreaterThan(0);
      expect(expectedKinds.transient ?? 0).toBeGreaterThan(0);
      expect(byFamily['B:sessionKeeper'].seeds).toBeGreaterThan(0);
      expect(byFamily['C:revokeApiSession'].seeds).toBeGreaterThan(0);
    }
    expect(
      broken.map(r => ({
        seed: r.seed,
        id: r.id.slice(0, 160),
        violations: r.violations,
      })),
    ).toEqual([]);
  });
});

// ─── Minimized reproductions of what the campaign found ──────────────────────

function sessionResponse(session: Record<string, unknown>): Response {
  return new Response(JSON.stringify({ session }), {
    status: 200,
    headers: { 'content-type': 'application/json' },
  });
}

describe('minimized findings (each fails until the module is hardened)', () => {
  it('F1a refreshApiSession: a finite expiresAt whose ×1000 overflows yields bearerExpiresAtMs=Infinity (contract: finite)', async () => {
    const tokens = await refreshApiSession(
      { apiBaseUrl: API, refreshToken: 'r0' },
      {
        fetchFn: async () =>
          sessionResponse({
            accessToken: 'a',
            refreshToken: 'b',
            expiresAt: Number.MAX_VALUE,
          }),
      },
    );
    expect(Number.isFinite(tokens.bearerExpiresAtMs)).toBe(true);
  });

  /**
   * setTimeout(fn, d) with d > 2^31-1 (or ±Infinity/NaN after the ×1000)
   * fires after 1 ms both in Node (the delay is clamped) and in jest's fake
   * timers; the keeper re-arms on every rotation, so a single oversized
   * expiry turns the documented ≥30 s rotation gap into a request per tick.
   * The threshold is exactly 2^31-1 ms ≈ 24.86 days from `now`.
   */
  const OVERFLOW_S = Math.ceil((2 ** 31 - 1) / 1000) + 61;
  it.each([
    ['expiresAt in milliseconds (1 h from now)', () => Date.now() + 3_600_000],
    ['expiresAt = 1e308 (×1000 → Infinity)', () => 1e308],
    [
      'expiresAt just past the 2^31-1 ms timer limit',
      () => NOW_S() + OVERFLOW_S,
    ],
  ])(
    'F1b sessionKeeper must not become a refresh storm when the server sends %s',
    async (_label, expiresAt) => {
      let n = 0;
      const times: number[] = [];
      const t0 = Date.now();
      startSessionKeeper({
        apiBaseUrl: API,
        refreshToken: 'r0',
        bearerExpiresAtMs: null,
        onRotated: () => undefined,
        onRevoked: () => undefined,
        fetchFn: async () => {
          n += 1;
          times.push(Date.now() - t0);
          if (n > STORM_KILL_PER_60S) stopSessionKeeper();
          return sessionResponse({
            accessToken: `a${n}`,
            refreshToken: `r${n}`,
            expiresAt: expiresAt(),
          });
        },
      });
      await jest.advanceTimersByTimeAsync(10 * 60_000);
      // 10 min at the documented ≥30 s rotation gap: 1 immediate + ≤20 re-arms.
      expect(maxInAnyWindow(times, 60_000)).toBeLessThanOrEqual(3);
      expect(n).toBeLessThanOrEqual(21);
    },
  );

  it('F1b (real Node timers, 300 ms wall): ms-scale expiresAt → a refresh request per timer tick', async () => {
    jest.useRealTimers();
    let n = 0;
    try {
      startSessionKeeper({
        apiBaseUrl: API,
        refreshToken: 'r0',
        bearerExpiresAtMs: null,
        onRotated: () => undefined,
        onRevoked: () => undefined,
        fetchFn: async () => {
          n += 1;
          if (n > STORM_KILL_PER_60S) stopSessionKeeper();
          return sessionResponse({
            accessToken: `a${n}`,
            refreshToken: `r${n}`,
            expiresAt: Date.now() + 3_600_000,
          });
        },
      });
      await new Promise(resolve => setTimeout(resolve, 300));
    } finally {
      stopSessionKeeper();
      await new Promise(resolve => setImmediate(resolve));
    }
    // Nothing is due for an hour: the immediate refresh is the only request.
    expect({ requestsIn300ms: n }).toEqual({ requestsIn300ms: 1 });
  });

  it('control: the same expiry 2 minutes INSIDE the 2^31-1 ms limit rotates once and re-arms 60 s ahead (HELD)', async () => {
    let n = 0;
    startSessionKeeper({
      apiBaseUrl: API,
      refreshToken: 'r0',
      bearerExpiresAtMs: null,
      onRotated: () => undefined,
      onRevoked: () => undefined,
      fetchFn: async () => {
        n += 1;
        return sessionResponse({
          accessToken: `a${n}`,
          refreshToken: `r${n}`,
          expiresAt: NOW_S() + OVERFLOW_S - 180,
        });
      },
    });
    await jest.advanceTimersByTimeAsync(10 * 60_000);
    expect(n).toBe(1);
  });

  it('F1c startSessionKeeper: a bearerExpiresAtMs of +Infinity / >2^31-1 ms ahead is refreshed after 1 ms instead of ahead of expiry', async () => {
    for (const bearerExpiresAtMs of [
      Number.POSITIVE_INFINITY,
      Date.now() + 2 ** 31 + 60_000,
    ]) {
      let n = 0;
      startSessionKeeper({
        apiBaseUrl: API,
        refreshToken: 'r0',
        bearerExpiresAtMs,
        onRotated: () => undefined,
        onRevoked: () => undefined,
        fetchFn: async () => {
          n += 1;
          if (n > STORM_KILL_PER_60S) stopSessionKeeper();
          return sessionResponse({
            accessToken: `a${n}`,
            refreshToken: `r${n}`,
            expiresAt: NOW_S() + 3600,
          });
        },
      });
      await jest.advanceTimersByTimeAsync(60_000);
      stopSessionKeeper();
      // Nothing is due for >24 days: zero requests in the first minute.
      expect({ bearerExpiresAtMs, requests: n }).toEqual({
        bearerExpiresAtMs,
        requests: 0,
      });
    }
  });

  it.each([
    ['fetch resolves null', 'resolve_null' as Transport],
    ['response has no json()', 'duck_no_json' as Transport],
    ['json() throws synchronously', 'duck_json_sync_throw' as Transport],
    ['json() returns a non-promise', 'duck_json_non_promise' as Transport],
  ])(
    'F2 refreshApiSession rejects with SessionRefreshError, never a raw TypeError: %s',
    async (_label, transport) => {
      const calls: Call[] = [];
      let error: unknown = null;
      try {
        await refreshApiSession(
          { apiBaseUrl: API, refreshToken: 'r0' },
          {
            fetchFn: fetchFor(
              { id: transport, status: 200, body: null, transport },
              calls,
            ),
          },
        );
      } catch (e) {
        error = e;
      }
      expect(error).toBeInstanceOf(SessionRefreshError);
      expect((error as SessionRefreshError).retryable).toBe(true);
    },
  );
});
