import type { ModelManifest, ModelManifestEntry } from "./registry.js";

/**
 * The honest manifest of what exists TODAY. Every entry is a real, shipping
 * implementation seeded with the version constant it actually exports in
 * this repo; absent tasks (court detection, camera calibration, temporal
 * encoder) are genuinely absent and simply have no entry — resolution
 * returns null and the fusion engine degrades honestly.
 *
 * Lineage fields are null-honest: no entry claims a training dataset,
 * splits, metrics, calibration, commit pin, or promotion date that was
 * never actually produced/recorded. When a trained model lands, it is
 * added here (or delivered via a remote manifest with an artifact hash)
 * — nothing else in the app changes.
 */

const CAPTURE_ENVELOPE = "capture-envelope-thresholds-v0.4-provisional";

/** Shared null-honest lineage defaults for pure-code, in-repo providers. */
const CODE_PROVIDER_LINEAGE = {
  inputSchemaVersion: 1,
  outputSchemaVersion: 1,
  artifactHash: null,
  artifactUri: null,
  trainingDatasetVersion: null,
  evaluationDatasetVersion: null,
  commit: null,
  splits: null,
  metrics: null,
  supportedCaptureEnvelope: null,
  calibrationVersion: null,
  runtimeRequirements: [] as string[],
  promotionDate: null,
  rollbackPredecessor: null,
  license: null,
} satisfies Partial<ModelManifestEntry>;

export const DEFAULT_MODEL_MANIFEST: ModelManifest = {
  schemaVersion: 1,
  entries: [
    {
      ...CODE_PROVIDER_LINEAGE,
      id: "pose.apple-vision",
      version: "apple-vision-bodypose-1",
      task: "pose_estimation",
      runtime: "vision_framework",
      executionTarget: "on_device",
      deploymentStatus: "production",
      supportedPlatforms: ["ios"],
      supportedStrokes: "all",
      supportedCaptureEnvelope: CAPTURE_ENVELOPE,
      runtimeRequirements: ["ios-vision-framework"],
      license: "apple-os-framework",
      notes:
        "Apple Vision body pose; real on-device inference. Per-coaching-metric accuracy not yet independently validated.",
    },
    {
      ...CODE_PROVIDER_LINEAGE,
      id: "pose.mediapipe",
      version: "mediapipe-pose-landmarker-1",
      task: "pose_estimation",
      runtime: "mediapipe",
      executionTarget: "on_device",
      deploymentStatus: "production",
      supportedPlatforms: ["android"],
      supportedStrokes: "all",
      supportedCaptureEnvelope: CAPTURE_ENVELOPE,
      runtimeRequirements: ["mediapipe-tasks-vision"],
      license: "apache-2.0",
      notes: "MediaPipe Pose Landmarker bundled with the Android build.",
    },
    {
      ...CODE_PROVIDER_LINEAGE,
      id: "trigger.temporal-heuristic",
      version: "temporal-stroke-heuristic-4",
      task: "stroke_trigger",
      runtime: "deterministic",
      executionTarget: "on_device",
      deploymentStatus: "production",
      supportedPlatforms: ["ios", "android"],
      supportedStrokes: "all",
      supportedCaptureEnvelope: CAPTURE_ENVELOPE,
      notes:
        "Wrist-kinematics clip trigger: hip-relative wrist speed in body-heights/s (distance-invariant since v3, walking-proof since v4: quiet onset + path gate). Detects THAT motion happened, never names it.",
    },
    {
      ...CODE_PROVIDER_LINEAGE,
      id: "trigger.offline",
      version: "offline-trigger-1",
      task: "stroke_trigger",
      runtime: "deterministic",
      executionTarget: "server",
      deploymentStatus: "production",
      supportedPlatforms: ["server"],
      supportedStrokes: "all",
      notes:
        "Offline wrist-kinematics trigger over recorded pose (OFFLINE_TRIGGER_VERSION in @pickle/vision-geometry offlineStroke).",
    },
    {
      ...CODE_PROVIDER_LINEAGE,
      id: "capture.completion-monitor",
      version: "capture-completion-params-v1",
      task: "capture_completion",
      runtime: "deterministic",
      executionTarget: "on_device",
      deploymentStatus: "production",
      supportedPlatforms: ["ios", "android"],
      supportedStrokes: "all",
      supportedCaptureEnvelope: CAPTURE_ENVELOPE,
      notes:
        "Clip-completion decision (CAPTURE_COMPLETION_PARAMS_V1, D-029). Default builds finalize a FIXED 1.5s post-roll; the adaptive settle-detection params are frozen for telemetry schema v1 and mirrored by the native StrokeCompletionMonitor.",
    },
    {
      ...CODE_PROVIDER_LINEAGE,
      id: "target.player-tracker",
      version: "player-track-1.1",
      task: "target_player_tracking",
      runtime: "deterministic",
      executionTarget: "server",
      deploymentStatus: "production",
      supportedPlatforms: ["server"],
      supportedStrokes: "all",
      notes:
        "Offline lab pipeline target-player track building and selection (PLAYER_TRACKER_VERSION), with explicit TARGET_* risk flags instead of silent identity claims.",
    },
    {
      ...CODE_PROVIDER_LINEAGE,
      id: "event.stroke-proposer",
      version: "stroke-event-1",
      task: "stroke_event_detection",
      runtime: "deterministic",
      executionTarget: "server",
      deploymentStatus: "production",
      supportedPlatforms: ["server"],
      supportedStrokes: "all",
      notes:
        "Stroke-event proposal over target wrist kinematics (STROKE_EVENT_VERSION, exported suffix '(heuristic, uncalibrated)'). Proposes event windows; never names strokes.",
    },
    {
      ...CODE_PROVIDER_LINEAGE,
      id: "paddle.dfine-detector",
      version: "dfine-medium-coco@transformers",
      task: "paddle_detection",
      runtime: "pytorch",
      executionTarget: "server",
      deploymentStatus: "production",
      supportedPlatforms: ["server"],
      supportedStrokes: "all",
      runtimeRequirements: ["python3.12", "torch", "transformers", "ffmpeg"],
      license: "apache-2.0",
      notes:
        "D-FINE medium, COCO-pretrained (tools/paddle-lab/detect_paddle.py DETECTOR_VERSION). NOT fine-tuned on paddles; weights come from the Hugging Face cache and are not hash-pinned in this repo — a known integrity gap recorded here rather than hidden.",
    },
    {
      ...CODE_PROVIDER_LINEAGE,
      id: "paddle.tracker",
      version: "paddle-track-2",
      task: "paddle_tracking",
      runtime: "deterministic",
      executionTarget: "server",
      deploymentStatus: "production",
      supportedPlatforms: ["server"],
      supportedStrokes: "all",
      notes:
        "ByteTrack-style two-stage association over raw detector candidates (PADDLE_TRACKER_VERSION). Misses are never interpolated into detections.",
    },
    {
      ...CODE_PROVIDER_LINEAGE,
      id: "paddle.primary-selector",
      version: "paddle-track-2",
      task: "paddle_selection",
      runtime: "deterministic",
      executionTarget: "server",
      deploymentStatus: "production",
      supportedPlatforms: ["server"],
      supportedStrokes: "all",
      notes:
        "Pose-GATED primary-track selection (selectPrimaryPaddleTrack). Ships inside PADDLE_TRACKER_VERSION and has no independent version constant; abstains with a reason when no track survives the gates.",
    },
    {
      ...CODE_PROVIDER_LINEAGE,
      id: "paddle.tracklet-merge",
      version: "paddle-track-2",
      task: "paddle_track_merge",
      runtime: "deterministic",
      executionTarget: "server",
      deploymentStatus: "production",
      supportedPlatforms: ["server"],
      supportedStrokes: "all",
      notes:
        "Tracklet merge (mergePaddleTracklets), shipped inside PADDLE_TRACKER_VERSION. merge-safety-v1 is the offline safety BENCH for this component, not its runtime version.",
    },
    {
      ...CODE_PROVIDER_LINEAGE,
      id: "paddle.ownership-verdict",
      version: "paddle-track-2",
      task: "paddle_ownership",
      runtime: "deterministic",
      executionTarget: "server",
      deploymentStatus: "production",
      supportedPlatforms: ["server"],
      supportedStrokes: "all",
      notes:
        "Wrist-affinity ownership verdict with flip-segmentation, computed inside the selector (PADDLE_TRACKER_VERSION). Wave-B/D red-team findings on wrong-owner families are preserved in swing-lab benches.",
    },
    {
      ...CODE_PROVIDER_LINEAGE,
      id: "paddle.ownership-guard",
      version: "ownership-guard-v1",
      task: "paddle_ownership",
      runtime: "deterministic",
      executionTarget: "server",
      deploymentStatus: "candidate",
      supportedPlatforms: ["server"],
      supportedStrokes: "all",
      notes:
        "OWNERSHIP_GUARD_VERSION (wave-D3 red team). OFF by default in production — registered as candidate, not production, because that is the truth.",
    },
    {
      ...CODE_PROVIDER_LINEAGE,
      id: "contact.ownership-posterior",
      version: "ownership-posterior-v1",
      task: "paddle_ownership",
      runtime: "deterministic",
      executionTarget: "server",
      deploymentStatus: "candidate",
      supportedPlatforms: ["server"],
      supportedStrokes: "all",
      notes:
        "CONTACT_OWNERSHIP_POSTERIOR_VERSION: contact posterior conditioned on ownership confidence. Flag-gated, default OFF — candidate, not production.",
    },
    {
      ...CODE_PROVIDER_LINEAGE,
      id: "ball.candidate-gate",
      version: "ball-candidate-gate-1",
      task: "ball_detection",
      runtime: "deterministic",
      executionTarget: "server",
      deploymentStatus: "production",
      supportedPlatforms: ["server"],
      supportedStrokes: "all",
      runtimeRequirements: ["python3.12", "numpy", "scipy", "ffmpeg"],
      license: "bsd-3-clause",
      notes:
        "BALL_CANDIDATE_GATE_VERSION: gates numpy/scipy blob candidates (tools/paddle-lab/ball_candidates.py — no learned model, no training).",
    },
    {
      ...CODE_PROVIDER_LINEAGE,
      id: "ball.tracker",
      version: "ball-track-2",
      task: "ball_tracking",
      runtime: "deterministic",
      executionTarget: "server",
      deploymentStatus: "production",
      supportedPlatforms: ["server"],
      supportedStrokes: "all",
      notes: "BALL_TRACKER_VERSION: ball track association over gated candidates.",
    },
    {
      ...CODE_PROVIDER_LINEAGE,
      id: "contact.evidence-estimator",
      version: "contact-evidence-4.4",
      task: "contact_estimation",
      runtime: "deterministic",
      executionTarget: "server",
      deploymentStatus: "production",
      supportedPlatforms: ["server"],
      supportedStrokes: "all",
      notes:
        "CONTACT_ESTIMATOR_VERSION: kernel-mass contact-moment evidence. Kernel widths were set on three dev gold cases only; offset priors are 0 because measured dev lead/lag had inconsistent sign — see offlineStroke.ts header.",
    },
    {
      ...CODE_PROVIDER_LINEAGE,
      id: "stroke.heuristic-hierarchical",
      version: "stroke-heuristic-5",
      task: "stroke_classification",
      runtime: "deterministic",
      executionTarget: "server",
      deploymentStatus: "deprecated",
      supportedPlatforms: ["server"],
      supportedStrokes: "all",
      notes:
        "Frozen v5 baseline (strokeHeuristicV5Frozen.ts, exported suffix '(uncalibrated)'). Kept as the registered rollback predecessor of stroke-heuristic-7.",
    },
    {
      ...CODE_PROVIDER_LINEAGE,
      id: "stroke.heuristic-hierarchical",
      version: "stroke-heuristic-7",
      task: "stroke_classification",
      runtime: "deterministic",
      executionTarget: "on_device",
      deploymentStatus: "production",
      supportedPlatforms: ["ios", "android", "server"],
      supportedStrokes: "all",
      rollbackPredecessor: "stroke.heuristic-hierarchical@stroke-heuristic-5",
      notes:
        "Hierarchical stroke heuristic (measured geometry, uncalibrated confidences; exported suffix '(uncalibrated)'). Commits at most a depth-2 side (FOREHAND/BACKHAND) or OVERHEAD as a depth-1 leaf; L3 needs bounce observation and is never claimed. Powers AUTO DETECT (declared-null routing) and declared-vs-predicted disagreement surfacing — it narrows nothing and never overrides a declaration.",
    },
    {
      ...CODE_PROVIDER_LINEAGE,
      id: "auto.declared-null-resolution",
      version: "fusion-1",
      task: "stroke_auto_resolution",
      runtime: "deterministic",
      executionTarget: "on_device",
      deploymentStatus: "production",
      supportedPlatforms: ["ios", "android", "server"],
      supportedStrokes: "all",
      notes:
        "AUTO DETECT declared-null profile resolution (strokeAutoResolution.ts). Ships inside FUSION_ENGINE_VERSION and has no independent version constant; resolution ladder is leaf → shared side profile → abstained, never an invented stroke.",
    },
    {
      ...CODE_PROVIDER_LINEAGE,
      id: "phase.geometry",
      version: "phase-geometry-1",
      task: "phase_segmentation",
      runtime: "deterministic",
      executionTarget: "on_device",
      deploymentStatus: "production",
      supportedPlatforms: ["ios", "android", "server"],
      supportedStrokes: "all",
      notes:
        "Deterministic wrist-kinematics phase segmentation. Upgrade path: learned temporal segmenter once labeled data exists.",
    },
    {
      ...CODE_PROVIDER_LINEAGE,
      id: "phase.paddle-temporal",
      version: "phase.paddle-temporal.v1",
      task: "phase_segmentation",
      runtime: "deterministic",
      executionTarget: "server",
      deploymentStatus: "experimental",
      supportedPlatforms: ["server"],
      supportedStrokes: "all",
      notes:
        "PHASE_TEMPORAL_VERSION (exported suffix '(heuristic, uncalibrated)'): paddle-kinematics phase proposal in swing-lab. Experimental — never shipped to the app pipeline.",
    },
    {
      ...CODE_PROVIDER_LINEAGE,
      id: "biomech.geometry",
      version: "features-geometry-1",
      task: "biomechanics_extraction",
      runtime: "deterministic",
      executionTarget: "on_device",
      deploymentStatus: "production",
      supportedPlatforms: ["ios", "android", "server"],
      supportedStrokes: "all",
      notes:
        "Measured 2D geometry features from recorded pose. One modality signal for fusion — not 'the model'.",
    },
    {
      ...CODE_PROVIDER_LINEAGE,
      id: "scorer.sm-v1",
      version: "sm-v1",
      task: "technique_scoring",
      runtime: "deterministic",
      executionTarget: "on_device",
      deploymentStatus: "production",
      supportedPlatforms: ["ios", "android", "server"],
      supportedStrokes: "all",
      notes:
        "Deterministic checkpoint scoring over measured biomechanics for every ShotTypeSlug. Targets are blueprint hypotheses pending coach-panel calibration; replaceable by a learned scorer under the same contract.",
    },
    {
      ...CODE_PROVIDER_LINEAGE,
      id: "faults.checkpoint-threshold",
      version: "faults-v1",
      task: "fault_detection",
      runtime: "deterministic",
      executionTarget: "on_device",
      deploymentStatus: "production",
      supportedPlatforms: ["ios", "android", "server"],
      supportedStrokes: "all",
      notes: "Faults derived from below-target checkpoint results with direction and severity.",
    },
    {
      ...CODE_PROVIDER_LINEAGE,
      id: "uncertainty.engine",
      version: "uncertainty-v1",
      task: "uncertainty_estimation",
      runtime: "deterministic",
      executionTarget: "on_device",
      deploymentStatus: "production",
      supportedPlatforms: ["ios", "android", "server"],
      supportedStrokes: "all",
      notes: "Confidence aggregation + abstention thresholds + limiting-factor reporting.",
    },
    {
      ...CODE_PROVIDER_LINEAGE,
      id: "coach.priority",
      version: "priority-v1",
      task: "coaching_ranking",
      runtime: "deterministic",
      executionTarget: "on_device",
      deploymentStatus: "production",
      supportedPlatforms: ["ios", "android", "server"],
      supportedStrokes: "all",
      notes: "Dependency-aware coaching priority (severity × confidence × coachability).",
    },
  ],
};
