import type { ModelManifest } from "./registry.js";

/**
 * The honest manifest of what exists TODAY. Every entry is a real, shipping
 * implementation; absent tasks (paddle, ball, court, classifier, temporal
 * encoder) are genuinely absent and simply have no entry — resolution
 * returns null and the fusion engine degrades honestly.
 *
 * When a trained model lands, it is added here (or delivered via a remote
 * manifest with an artifact hash) — nothing else in the app changes.
 */
export const DEFAULT_MODEL_MANIFEST: ModelManifest = {
  schemaVersion: 1,
  entries: [
    {
      id: "pose.apple-vision",
      version: "apple-vision-bodypose-1",
      task: "pose_estimation",
      runtime: "vision_framework",
      executionTarget: "on_device",
      deploymentStatus: "production",
      supportedPlatforms: ["ios"],
      supportedStrokes: "all",
      inputSchemaVersion: 1,
      outputSchemaVersion: 1,
      artifactHash: null,
      artifactUri: null,
      trainingDatasetVersion: null,
      evaluationDatasetVersion: null,
      license: "apple-os-framework",
      notes:
        "Apple Vision body pose; real on-device inference. Per-coaching-metric accuracy not yet independently validated.",
    },
    {
      id: "pose.mediapipe",
      version: "mediapipe-pose-landmarker-1",
      task: "pose_estimation",
      runtime: "mediapipe",
      executionTarget: "on_device",
      deploymentStatus: "production",
      supportedPlatforms: ["android"],
      supportedStrokes: "all",
      inputSchemaVersion: 1,
      outputSchemaVersion: 1,
      artifactHash: null,
      artifactUri: null,
      trainingDatasetVersion: null,
      evaluationDatasetVersion: null,
      license: "apache-2.0",
      notes: "MediaPipe Pose Landmarker bundled with the Android build.",
    },
    {
      id: "trigger.temporal-heuristic",
      version: "temporal-stroke-heuristic-2",
      task: "stroke_trigger",
      runtime: "deterministic",
      executionTarget: "on_device",
      deploymentStatus: "production",
      supportedPlatforms: ["ios", "android"],
      supportedStrokes: "all",
      inputSchemaVersion: 1,
      outputSchemaVersion: 1,
      artifactHash: null,
      artifactUri: null,
      trainingDatasetVersion: null,
      evaluationDatasetVersion: null,
      license: null,
      notes: "Wrist-kinematics clip trigger. Detects THAT motion happened, never names it.",
    },
    {
      id: "stroke.heuristic-hierarchical",
      version: "stroke-heuristic-1",
      task: "stroke_classification",
      runtime: "deterministic",
      executionTarget: "on_device",
      deploymentStatus: "production",
      supportedPlatforms: ["ios", "android", "server"],
      supportedStrokes: "all",
      inputSchemaVersion: 1,
      outputSchemaVersion: 1,
      artifactHash: null,
      artifactUri: null,
      trainingDatasetVersion: null,
      evaluationDatasetVersion: null,
      license: null,
      notes:
        "Hierarchical stroke heuristic (measured geometry, uncalibrated confidences). Commits at most a depth-2 side (FOREHAND/BACKHAND) or OVERHEAD as a depth-1 leaf; L3 needs bounce observation and is never claimed. Powers AUTO DETECT (declared-null routing) and declared-vs-predicted disagreement surfacing — it narrows nothing and never overrides a declaration.",
    },
    {
      id: "phase.geometry",
      version: "phase-geometry-1",
      task: "phase_segmentation",
      runtime: "deterministic",
      executionTarget: "on_device",
      deploymentStatus: "production",
      supportedPlatforms: ["ios", "android", "server"],
      supportedStrokes: "all",
      inputSchemaVersion: 1,
      outputSchemaVersion: 1,
      artifactHash: null,
      artifactUri: null,
      trainingDatasetVersion: null,
      evaluationDatasetVersion: null,
      license: null,
      notes:
        "Deterministic wrist-kinematics phase segmentation. Upgrade path: learned temporal segmenter once labeled data exists.",
    },
    {
      id: "biomech.geometry",
      version: "features-geometry-1",
      task: "biomechanics_extraction",
      runtime: "deterministic",
      executionTarget: "on_device",
      deploymentStatus: "production",
      supportedPlatforms: ["ios", "android", "server"],
      supportedStrokes: "all",
      inputSchemaVersion: 1,
      outputSchemaVersion: 1,
      artifactHash: null,
      artifactUri: null,
      trainingDatasetVersion: null,
      evaluationDatasetVersion: null,
      license: null,
      notes:
        "Measured 2D geometry features from recorded pose. One modality signal for fusion — not 'the model'.",
    },
    {
      id: "scorer.sm-v1",
      version: "sm-v1",
      task: "technique_scoring",
      runtime: "deterministic",
      executionTarget: "on_device",
      deploymentStatus: "production",
      supportedPlatforms: ["ios", "android", "server"],
      supportedStrokes: ["forehand_drive", "dink", "third_shot_drop", "serve"],
      inputSchemaVersion: 1,
      outputSchemaVersion: 1,
      artifactHash: null,
      artifactUri: null,
      trainingDatasetVersion: null,
      evaluationDatasetVersion: null,
      license: null,
      notes:
        "Deterministic checkpoint scoring over measured biomechanics. Targets are blueprint hypotheses pending coach-panel calibration; replaceable by a learned scorer under the same contract.",
    },
    {
      id: "faults.checkpoint-threshold",
      version: "faults-v1",
      task: "fault_detection",
      runtime: "deterministic",
      executionTarget: "on_device",
      deploymentStatus: "production",
      supportedPlatforms: ["ios", "android", "server"],
      supportedStrokes: "all",
      inputSchemaVersion: 1,
      outputSchemaVersion: 1,
      artifactHash: null,
      artifactUri: null,
      trainingDatasetVersion: null,
      evaluationDatasetVersion: null,
      license: null,
      notes: "Faults derived from below-target checkpoint results with direction and severity.",
    },
    {
      id: "uncertainty.engine",
      version: "uncertainty-v1",
      task: "uncertainty_estimation",
      runtime: "deterministic",
      executionTarget: "on_device",
      deploymentStatus: "production",
      supportedPlatforms: ["ios", "android", "server"],
      supportedStrokes: "all",
      inputSchemaVersion: 1,
      outputSchemaVersion: 1,
      artifactHash: null,
      artifactUri: null,
      trainingDatasetVersion: null,
      evaluationDatasetVersion: null,
      license: null,
      notes: "Confidence aggregation + abstention thresholds + limiting-factor reporting.",
    },
    {
      id: "coach.priority",
      version: "priority-v1",
      task: "coaching_ranking",
      runtime: "deterministic",
      executionTarget: "on_device",
      deploymentStatus: "production",
      supportedPlatforms: ["ios", "android", "server"],
      supportedStrokes: "all",
      inputSchemaVersion: 1,
      outputSchemaVersion: 1,
      artifactHash: null,
      artifactUri: null,
      trainingDatasetVersion: null,
      evaluationDatasetVersion: null,
      license: null,
      notes: "Dependency-aware coaching priority (severity × confidence × coachability).",
    },
  ],
};
