// STRESS — `POST /v1/auth/refresh` under the CONCURRENCY lens.
//
// Drives the REAL production handler (supabase/functions/api/index.ts, loaded
// in-process by xc_concurrency_harness.ts with Supabase Auth / PostgREST /
// RevenueCat stubbed at the fetch layer; no network, no hosted project) with
// Promise.all bursts generated by a seeded scheduler. Every iteration is a
// program derived from ONE seed (policy, latency, actors, ops, per-op start
// delays, abort points), so any row of the JSON table replays exactly with
// `STRESS_SEED=<seed> STRESS_ITER=1`.
//
// Campaigns (each writes artifacts/stress-auth-refresh-concurrency/latest/*.json):
//   A  randomized interleavings — duplicate refresh, chained refresh
//      (call-during-call), client abort mid-call, two devices on one session,
//      logout racing refresh, garbage tokens, body stream failure mid-read.
//   B  cancel-during-call — the client abandons the request at a random point;
//      the rotation the server may have completed must never be lost/duplicated.
//   C  per-IP refresh budget under a same-IP burst — exactly 30 admitted,
//      auth-failure budget charged once per 401 and enforced afterwards.
//   D  clock skew between GoTrue and the edge — a 200 never hands out a bearer
//      that is already dead; an already-expired upstream session is 503 (retry)
//      not 401 (sign out).
//   E  GoTrue hangs / drops the connection under a burst — every request ends
//      inside the deadline as 503 + Retry-After; the refresh token stays alive.
//   F  logout racing refresh across two devices sharing a session — after both
//      settle, nothing of that session authenticates; no 5xx.
//
// Scale: STRESS_ITER (default 24 so the suite stays fast; the campaign that
// produced the recorded evidence ran STRESS_ITER=600). STRESS_SEED picks the
// base seed; iteration i uses seed STRESS_SEED + i.

import { assert, assertEquals } from "@std/assert";
import {
  b64url,
  bootstrap,
  edgeRequest,
  envInt,
  type FakeSession,
  histogram,
  isRecord,
  jwtPayload,
  loadXcHarness,
  Prng,
  readJson,
  type RefreshPolicy,
  sleep,
  type XcHarness,
} from "./xc_concurrency_harness.ts";

// ─────────────────────────────────────────────────────────────────────────────
// Knobs
// ─────────────────────────────────────────────────────────────────────────────

const STRESS_SEED = envInt("STRESS_SEED", 20260904);
const STRESS_ITER = envInt("STRESS_ITER", 24);
/** Per-iteration wall-time bound (ms). Latency per hop ≤ 20ms, ≤ 4 sequential
 * hops per op, so a healthy iteration is < 500ms; 3s means "no deadlock". */
const ITERATION_BOUND_MS = envInt("STRESS_BOUND_MS", 3_000);
const AUTH_REFRESH_LIMIT = 30;
const AUTH_FAILURE_LIMIT = 30;

function outDir(): string {
  const dir = Deno.env.get("STRESS_OUT_DIR") ??
    new URL(
      "../../../../artifacts/stress-auth-refresh-concurrency/latest/",
      import.meta.url,
    )
      .pathname;
  Deno.mkdirSync(dir, { recursive: true });
  return dir.endsWith("/") ? dir : `${dir}/`;
}

function replay(campaign: string, seed: number, extra = ""): string {
  return (
    `cd supabase/functions/api/__wf__ && STRESS_SEED=${seed} STRESS_ITER=1 ${extra}` +
    `deno test -A --no-check --config deno.json stress_auth_refresh_concurrency.test.ts ` +
    `--filter "stress ${campaign}"`
  ).replace(/\s+/g, " ");
}

// ─────────────────────────────────────────────────────────────────────────────
// Upstream interception layered over the harness fetch: counts every GoTrue
// refresh exchange by status, records every pair GoTrue minted (the ground
// truth for "no lost update / no duplicate session"), and can apply clock
// skew, hang until the caller's deadline aborts, or drop the connection.
// ─────────────────────────────────────────────────────────────────────────────

interface Upstream {
  refreshCalls: number;
  refreshStatus: Record<string, number>;
  /** access_token → refresh_token of every 200 GoTrue refresh reply. */
  minted: Map<string, string>;
  /** GoTrue's clock minus the edge's clock, in seconds (0 = in sync). */
  skewSeconds: number;
  mode: "pass" | "hang" | "connection-reset";
  reset(): void;
}

let upstreamState: Upstream | null = null;

function abortError(): DOMException {
  return new DOMException("The signal has been aborted", "AbortError");
}

function hangUntilAborted(
  signal: AbortSignal | null | undefined,
): Promise<Response> {
  return new Promise((_, reject) => {
    if (!signal) return; // no deadline → genuinely hangs; the harness never does this
    if (signal.aborted) {
      reject(abortError());
      return;
    }
    signal.addEventListener("abort", () => reject(abortError()), {
      once: true,
    });
  });
}

/** Access tokens already re-stamped with GoTrue's skewed clock; a reuse-window
 * replay returns the SAME token again and must not be skewed twice. */
const skewedTokens = new Set<string>();

function skewSession(
  h: XcHarness,
  body: Record<string, unknown>,
  skewSeconds: number,
): Record<string, unknown> {
  const accessToken = typeof body.access_token === "string"
    ? body.access_token
    : "";
  if (skewedTokens.has(accessToken)) return body;
  const payload = jwtPayload(accessToken);
  if (!payload || typeof payload.exp !== "number") return body;
  const [header] = accessToken.split(".");
  const skewed = `${header}.${
    b64url(JSON.stringify({ ...payload, exp: payload.exp + skewSeconds }))
  }.sig`;
  skewedTokens.add(skewed);
  const sid = h.fake.accessIndex.get(accessToken);
  if (sid) {
    const session = h.fake.sessions.get(sid);
    h.fake.accessIndex.delete(accessToken);
    h.fake.accessIndex.set(skewed, sid);
    if (session && session.accessToken === accessToken) {
      session.accessToken = skewed;
    }
  }
  return {
    ...body,
    access_token: skewed,
    expires_at: typeof body.expires_at === "number"
      ? body.expires_at + skewSeconds
      : body.expires_at,
  };
}

async function loadStressHarness(): Promise<{ h: XcHarness; up: Upstream }> {
  const h = await loadXcHarness();
  if (upstreamState) return { h, up: upstreamState };
  const up: Upstream = {
    refreshCalls: 0,
    refreshStatus: {},
    minted: new Map(),
    skewSeconds: 0,
    mode: "pass",
    reset() {
      this.refreshCalls = 0;
      this.refreshStatus = {};
      this.minted = new Map();
      this.skewSeconds = 0;
      this.mode = "pass";
    },
  };
  const inner = globalThis.fetch;
  globalThis.fetch = (async (
    input: RequestInfo | URL,
    init?: RequestInit,
  ): Promise<Response> => {
    const url = new URL(
      typeof input === "string"
        ? input
        : input instanceof URL
        ? input
        : input.url,
    );
    const isRefresh = url.pathname === "/auth/v1/token" &&
      url.searchParams.get("grant_type") === "refresh_token";
    if (!isRefresh) return inner(input, init);
    up.refreshCalls += 1;
    if (up.mode === "hang") {
      up.refreshStatus.hang = (up.refreshStatus.hang ?? 0) + 1;
      return await hangUntilAborted(init?.signal);
    }
    if (up.mode === "connection-reset") {
      up.refreshStatus.reset = (up.refreshStatus.reset ?? 0) + 1;
      throw new TypeError("stress: connection reset by peer");
    }
    const response = await inner(input, init);
    up.refreshStatus[response.status] =
      (up.refreshStatus[response.status] ?? 0) + 1;
    if (response.status !== 200) return response;
    let body = (await response.clone().json().catch(() => null)) as
      | Record<string, unknown>
      | null;
    if (!isRecord(body)) return response;
    if (up.skewSeconds !== 0) body = skewSession(h, body, up.skewSeconds);
    if (
      typeof body.access_token === "string" &&
      typeof body.refresh_token === "string"
    ) {
      up.minted.set(body.access_token, body.refresh_token);
    }
    return new Response(JSON.stringify(body), {
      status: 200,
      headers: response.headers,
    });
  }) as typeof fetch;
  upstreamState = up;
  return { h, up };
}

// ─────────────────────────────────────────────────────────────────────────────
// Scheduler + program model
// ─────────────────────────────────────────────────────────────────────────────

let ipCounter = 0;
/** Fresh CGNAT address per actor → each actor owns its own rate-limit windows
 * (the campaign is about session correctness; C tests the limiter itself). */
function nextIp(): string {
  ipCounter += 1;
  return `100.64.${(ipCounter >> 8) & 255}.${ipCounter & 255}`;
}

interface Actor {
  /** "device" index; two devices may share one session (cloned device). */
  id: number;
  userSub: string;
  userId: string;
  sessionId: string;
  ip: string;
  accessToken: string;
  refreshToken: string;
}

type OpKind =
  | "dup" // refresh(rt0) — the stored token, possibly many times at once
  | "chain" // refresh(rt0) then immediately refresh(result) — call during call
  | "abort" // refresh(rt0) abandoned by the client after a few ms
  | "logout" // POST /v1/auth/logout with the device's bearer
  | "probe" // GET /v1/me/access with the device's bearer (session must stay coherent)
  | "garbage" // refresh(<token that never existed>)
  | "body-error"; // body stream fails mid-read

interface Op {
  index: number;
  actor: number;
  kind: OpKind;
  startDelayMs: number;
  abortAfterMs?: number;
}

interface OpResult {
  index: number;
  actor: number;
  kind: OpKind;
  /** HTTP statuses observed by THIS op in order (chain has two). */
  statuses: number[];
  /** "client-aborted" means the client stopped waiting; the server response
   * (still recorded in statuses) was discarded client-side. */
  clientOutcome: "response" | "client-aborted";
  durationMs: number;
  /** Refresh tokens the op SENT, in order. */
  sent: string[];
  /** Sessions returned by 200 refresh replies (access → refresh). */
  received: Array<
    { accessToken: string; refreshToken: string; expiresAt: number }
  >;
}

interface Invariant {
  name: string;
  holds: boolean;
  detail: string;
}

interface IterationRow {
  campaign: string;
  iteration: number;
  seed: number;
  policy: RefreshPolicy;
  latencyMaxMs: number;
  actors: Array<
    {
      id: number;
      ip: string;
      sessionId: string;
      sharesSessionWith: number | null;
    }
  >;
  ops: Op[];
  results: OpResult[];
  edgeStatusHistogram: Record<string, number>;
  upstream: {
    refreshCalls: number;
    refreshStatus: Record<string, number>;
    minted: number;
  };
  invariants: Invariant[];
  holds: boolean;
  durationMs: number;
  replay: string;
}

function inv(
  list: Invariant[],
  name: string,
  holds: boolean,
  detail: string,
): void {
  list.push({ name, holds, detail });
}

function pick<T>(prng: Prng, weighted: Array<[T, number]>): T {
  const total = weighted.reduce((sum, [, w]) => sum + w, 0);
  let roll = prng.next() * total;
  for (const [value, weight] of weighted) {
    roll -= weight;
    if (roll < 0) return value;
  }
  return weighted[weighted.length - 1][0];
}

function sessionOf(body: Record<string, unknown>) {
  const session = isRecord(body.session) ? body.session : null;
  if (!session) return null;
  const accessToken = session.accessToken;
  const refreshToken = session.refreshToken;
  const expiresAt = session.expiresAt;
  if (
    typeof accessToken !== "string" || !accessToken ||
    typeof refreshToken !== "string" ||
    !refreshToken || typeof expiresAt !== "number" ||
    !Number.isFinite(expiresAt)
  ) {
    return null;
  }
  return { accessToken, refreshToken, expiresAt };
}

function refreshRequest(ip: string, refreshToken: string): Request {
  return edgeRequest("POST", "/v1/auth/refresh", {
    ip,
    body: { refreshToken },
  });
}

/** A refresh request whose JSON body stream errors after the first half. */
function brokenBodyRefreshRequest(ip: string, refreshToken: string): Request {
  const text = JSON.stringify({ refreshToken });
  const half = new TextEncoder().encode(
    text.slice(0, Math.floor(text.length / 2)),
  );
  const body = new ReadableStream<Uint8Array>({
    start(controller) {
      controller.enqueue(half);
      controller.error(
        new TypeError("stress: client connection dropped mid-body"),
      );
    },
  });
  return new Request("http://edge.xc.test/functions/v1/api/v1/auth/refresh", {
    method: "POST",
    headers: { "content-type": "application/json", "x-forwarded-for": ip },
    body,
  });
}

async function mintActor(h: XcHarness, prng: Prng, id: number): Promise<Actor> {
  const userSub = `stress-${prng.uuid()}`;
  const boot = await bootstrap(h, userSub, nextIp());
  assertEquals(
    boot.status,
    200,
    `bootstrap failed: ${JSON.stringify(boot.body)}`,
  );
  const payload = jwtPayload(boot.accessToken);
  return {
    id,
    userSub,
    userId: String(payload?.sub ?? ""),
    sessionId: String(payload?.session_id ?? ""),
    ip: nextIp(),
    accessToken: boot.accessToken,
    refreshToken: boot.refreshToken,
  };
}

async function runOp(h: XcHarness, actor: Actor, op: Op): Promise<OpResult> {
  const started = performance.now();
  const result: OpResult = {
    index: op.index,
    actor: op.actor,
    kind: op.kind,
    statuses: [],
    clientOutcome: "response",
    durationMs: 0,
    sent: [],
    received: [],
  };
  if (op.startDelayMs > 0) await sleep(op.startDelayMs);

  const refreshOnce = async (
    request: Request,
    sent: string,
  ): Promise<Response> => {
    result.sent.push(sent);
    const response = await h.handler(request);
    result.statuses.push(response.status);
    const body = await readJson(response);
    if (response.status === 200) {
      const session = sessionOf(body);
      if (session) result.received.push(session);
      else result.statuses.push(-200); // 200 without a usable session: flagged
    }
    return response;
  };

  switch (op.kind) {
    case "dup": {
      await refreshOnce(
        refreshRequest(actor.ip, actor.refreshToken),
        actor.refreshToken,
      );
      break;
    }
    case "chain": {
      await refreshOnce(
        refreshRequest(actor.ip, actor.refreshToken),
        actor.refreshToken,
      );
      const first = result.received[0];
      if (first) {
        await refreshOnce(
          refreshRequest(actor.ip, first.refreshToken),
          first.refreshToken,
        );
      }
      break;
    }
    case "abort": {
      const controller = new AbortController();
      const request = new Request(
        refreshRequest(actor.ip, actor.refreshToken),
        {
          signal: controller.signal,
        },
      );
      const server = refreshOnce(request, actor.refreshToken);
      let timer: ReturnType<typeof setTimeout> | undefined;
      const clientGaveUp = new Promise<"client-aborted">((resolve) => {
        timer = setTimeout(() => {
          controller.abort();
          resolve("client-aborted");
        }, op.abortAfterMs ?? 0);
      });
      const winner = await Promise.race([
        server.then(() => "response" as const),
        clientGaveUp,
      ]);
      if (winner === "client-aborted") result.clientOutcome = "client-aborted";
      else clearTimeout(timer);
      // The real server keeps running after a client disconnect; keep the
      // outcome for the oracle (it is what GoTrue actually did).
      await server;
      break;
    }
    case "logout": {
      const response = await h.handler(
        edgeRequest("POST", "/v1/auth/logout", {
          ip: actor.ip,
          token: actor.accessToken,
        }),
      );
      result.statuses.push(response.status);
      await response.body?.cancel();
      break;
    }
    case "probe": {
      const response = await h.handler(
        edgeRequest("GET", "/v1/me/access", {
          ip: actor.ip,
          token: actor.accessToken,
        }),
      );
      result.statuses.push(response.status);
      await response.body?.cancel();
      break;
    }
    case "garbage": {
      const garbage = `rt-0.0-garbage-${op.index}-${actor.id}`;
      await refreshOnce(refreshRequest(actor.ip, garbage), garbage);
      break;
    }
    case "body-error": {
      const response = await h.handler(
        brokenBodyRefreshRequest(actor.ip, actor.refreshToken),
      );
      result.statuses.push(response.status);
      const body = await readJson(response);
      const code = isRecord(body.error) ? body.error.code : undefined;
      if (response.status === 400 && code !== "validation.refresh") {
        result.statuses.push(-400);
      }
      break;
    }
  }
  result.durationMs = Math.round((performance.now() - started) * 100) / 100;
  return result;
}

/** Every access token that ever belonged to a session (bootstrap + rotations). */
function tokensOfSession(
  h: XcHarness,
  sessionId: string,
  actors: Actor[],
  results: OpResult[],
) {
  const access = new Set<string>();
  const refresh = new Set<string>();
  for (const actor of actors) {
    if (actor.sessionId !== sessionId) continue;
    access.add(actor.accessToken);
    refresh.add(actor.refreshToken);
  }
  for (const result of results) {
    const actor = actors[result.actor];
    if (actor.sessionId !== sessionId) continue;
    for (const session of result.received) {
      access.add(session.accessToken);
      refresh.add(session.refreshToken);
    }
  }
  const fakeSession = h.fake.sessions.get(sessionId);
  if (fakeSession) {
    access.add(fakeSession.accessToken);
    refresh.add(fakeSession.refreshToken);
  }
  return { access, refresh };
}

// ─────────────────────────────────────────────────────────────────────────────
// Campaign A — randomized interleavings
// ─────────────────────────────────────────────────────────────────────────────

async function iterationA(
  h: XcHarness,
  up: Upstream,
  iteration: number,
  seed: number,
): Promise<IterationRow> {
  const prng = new Prng(seed);
  const policy: RefreshPolicy = prng.next() < 0.7
    ? "rotate-reject-reuse"
    : "rotate-reuse-window";
  const latencyMaxMs = prng.int(0, 20);
  h.fake.reset(seed, latencyMaxMs);
  h.fake.refreshPolicy = policy;
  up.reset();

  // Actors: 1 device, 2 devices on 2 sessions (same or different users), or
  // 2 devices sharing ONE session (a cloned refresh token — two actors on the
  // same row).
  const shape = pick(prng, [
    ["single", 45],
    ["two-sessions", 25],
    ["cloned-device", 30],
  ] as Array<[string, number]>);
  const actors: Actor[] = [await mintActor(h, prng, 0)];
  if (shape === "two-sessions") actors.push(await mintActor(h, prng, 1));
  if (shape === "cloned-device") {
    actors.push({ ...actors[0], id: 1, ip: nextIp() });
  }

  const opCount = prng.int(2, 8);
  const ops: Op[] = [];
  for (let i = 0; i < opCount; i++) {
    const kind = pick(prng, [
      ["dup", 34],
      ["chain", 18],
      ["abort", 12],
      ["logout", 10],
      ["probe", 12],
      ["garbage", 8],
      ["body-error", 6],
    ] as Array<[OpKind, number]>);
    const op: Op = {
      index: i,
      actor: actors.length === 1 ? 0 : prng.int(0, actors.length - 1),
      kind,
      startDelayMs: prng.int(0, 15),
    };
    if (kind === "abort") op.abortAfterMs = prng.int(0, 12);
    ops.push(op);
  }

  const started = performance.now();
  const results = await Promise.all(
    ops.map((op) => runOp(h, actors[op.actor], op)),
  );
  const durationMs = Math.round(performance.now() - started);

  const invariants: Invariant[] = [];
  const statuses = results.flatMap((r) => r.statuses);
  inv(
    invariants,
    "bounded wall time (no deadlock)",
    durationMs <= ITERATION_BOUND_MS,
    `${durationMs}ms ≤ ${ITERATION_BOUND_MS}ms`,
  );
  inv(
    invariants,
    "no 5xx and no malformed 200/400 body",
    statuses.every((s) => s < 500 && s > 0),
    `statuses=${JSON.stringify(histogram(statuses))}`,
  );
  const refreshOps = results.filter((r) =>
    r.kind !== "logout" && r.kind !== "probe"
  );
  const edgeRefresh = histogram(
    refreshOps.filter((r) => r.kind !== "body-error").flatMap((r) =>
      r.statuses
    ),
  );
  const upstreamOk = up.refreshStatus["200"] ?? 0;
  const upstreamRefused = (up.refreshStatus["400"] ?? 0) +
    (up.refreshStatus["401"] ?? 0) +
    (up.refreshStatus["403"] ?? 0);
  const upstreamOther = up.refreshCalls - upstreamOk - upstreamRefused;
  inv(
    invariants,
    "edge status ⇔ GoTrue verdict (200↔200, 401↔refusal, 503↔anything else)",
    (edgeRefresh["200"] ?? 0) === upstreamOk &&
      (edgeRefresh["401"] ?? 0) === upstreamRefused &&
      (edgeRefresh["503"] ?? 0) === upstreamOther &&
      upstreamOther === 0,
    `edge=${JSON.stringify(edgeRefresh)} gotrue=${
      JSON.stringify(up.refreshStatus)
    }`,
  );
  inv(
    invariants,
    "body-error requests are 400 validation.refresh, never 5xx, never reach GoTrue",
    results.filter((r) => r.kind === "body-error").every((r) =>
      r.statuses.join() === "400"
    ),
    JSON.stringify(
      results.filter((r) => r.kind === "body-error").map((r) => r.statuses),
    ),
  );

  // Every session the edge handed out is one GoTrue minted for THAT
  // session/user, and every mint GoTrue performed reached exactly one reply
  // (no lost update, no duplicate/forged session).
  const delivered = new Map<string, string>();
  let crossLeak = 0;
  let duplicateDelivery = 0;
  let deadOnArrival = 0;
  for (const result of results) {
    const actor = actors[result.actor];
    for (const session of result.received) {
      const payload = jwtPayload(session.accessToken);
      if (
        payload?.sub !== actor.userId || payload?.session_id !== actor.sessionId
      ) crossLeak++;
      if (session.expiresAt * 1000 <= Date.now()) deadOnArrival++;
      if (
        policy === "rotate-reject-reuse" && delivered.has(session.accessToken)
      ) {
        duplicateDelivery++;
      }
      delivered.set(session.accessToken, session.refreshToken);
    }
  }
  inv(
    invariants,
    "no cross-session / cross-user token in any reply",
    crossLeak === 0,
    `leaks=${crossLeak}`,
  );
  inv(
    invariants,
    "no dead-on-arrival session (expiresAt in the past)",
    deadOnArrival === 0,
    `dead=${deadOnArrival}`,
  );
  const mintedPairs = [...up.minted.entries()].map(([a, r]) => `${a}|${r}`)
    .sort();
  const deliveredPairs = [...delivered.entries()].map(([a, r]) => `${a}|${r}`)
    .sort();
  inv(
    invariants,
    "delivered sessions == GoTrue-minted sessions (no lost update, no forged session)",
    JSON.stringify(mintedPairs) === JSON.stringify(deliveredPairs) &&
      (policy === "rotate-reuse-window" || duplicateDelivery === 0),
    `minted=${mintedPairs.length} delivered=${deliveredPairs.length} duplicateDelivery=${duplicateDelivery}`,
  );

  // Rotation semantics per input refresh token.
  const perToken = new Map<string, number>();
  for (const result of refreshOps) {
    result.sent.forEach((token, i) => {
      if (result.statuses[i] === 200) {
        perToken.set(token, (perToken.get(token) ?? 0) + 1);
      }
    });
  }
  const multiSuccess = [...perToken.values()].filter((n) => n > 1).length;
  inv(
    invariants,
    policy === "rotate-reject-reuse"
      ? "reject-reuse: a refresh token succeeds at most once (no double spend of a rotation)"
      : "reuse-window: replays return already-minted sessions only (checked above)",
    policy === "rotate-reuse-window" || multiSuccess === 0,
    `tokensWithMultipleSuccesses=${multiSuccess}`,
  );
  inv(
    invariants,
    "garbage refresh tokens are always 401 (never 200/5xx)",
    results.filter((r) => r.kind === "garbage").every((r) =>
      r.statuses.join() === "401"
    ),
    JSON.stringify(
      results.filter((r) => r.kind === "garbage").map((r) => r.statuses),
    ),
  );

  // Post-state oracle against the model: a session that saw a 204 logout is
  // dead everywhere; otherwise its NEWEST refresh token still rotates.
  const probeIp = nextIp();
  const sessionIds = [...new Set(actors.map((a) => a.sessionId))];
  const postState: string[] = [];
  for (const sessionId of sessionIds) {
    const owners = actors.filter((a) => a.sessionId === sessionId).map((a) =>
      a.id
    );
    const loggedOut = results.some(
      (r) =>
        r.kind === "logout" && owners.includes(r.actor) &&
        r.statuses[0] === 204,
    );
    const tokens = tokensOfSession(h, sessionId, actors, results);
    const fakeSession = h.fake.sessions.get(sessionId) as
      | FakeSession
      | undefined;
    if (loggedOut) {
      const probes = await Promise.all(
        [...tokens.access].map((token) =>
          h.handler(edgeRequest("GET", "/v1/me/access", { ip: probeIp, token }))
            .then(
              async (r) => {
                await r.body?.cancel();
                return r.status;
              },
            )
        ),
      );
      const refreshes = await Promise.all(
        [...tokens.refresh].map((token) =>
          h.handler(refreshRequest(nextIp(), token)).then(async (r) => {
            await r.body?.cancel();
            return r.status;
          })
        ),
      );
      const dead = probes.every((s) => s === 401) &&
        refreshes.every((s) => s === 401);
      postState.push(
        `${sessionId}: logged out → bearers=${
          JSON.stringify(histogram(probes))
        } refresh=${JSON.stringify(histogram(refreshes))}`,
      );
      inv(
        invariants,
        `logout is total for ${sessionId}`,
        dead && fakeSession?.revoked === true,
        postState[postState.length - 1],
      );
    } else {
      assert(fakeSession, `model lost session ${sessionId}`);
      const live = await h.handler(
        refreshRequest(nextIp(), fakeSession.refreshToken),
      );
      const liveBody = await readJson(live);
      const liveSession = sessionOf(liveBody);
      const bearer = liveSession
        ? await h.handler(
          edgeRequest("GET", "/v1/me/access", {
            ip: probeIp,
            token: liveSession.accessToken,
          }),
        )
        : null;
      if (bearer) await bearer.body?.cancel();
      postState.push(
        `${sessionId}: alive → newest refresh=${live.status} bearer=${
          bearer?.status ?? "n/a"
        }`,
      );
      inv(
        invariants,
        `session ${sessionId} still rotates after the burst (no spurious revocation)`,
        live.status === 200 && bearer?.status === 200 &&
          fakeSession.revoked === false,
        postState[postState.length - 1],
      );
    }
  }

  return {
    campaign: "A",
    iteration,
    seed,
    policy,
    latencyMaxMs,
    actors: actors.map((a) => ({
      id: a.id,
      ip: a.ip,
      sessionId: a.sessionId,
      sharesSessionWith:
        actors.find((o) => o.id !== a.id && o.sessionId === a.sessionId)?.id ??
          null,
    })),
    ops,
    results,
    edgeStatusHistogram: histogram(statuses),
    upstream: {
      refreshCalls: up.refreshCalls,
      refreshStatus: up.refreshStatus,
      minted: up.minted.size,
    },
    invariants,
    holds: invariants.every((i) => i.holds),
    durationMs,
    replay: replay("A", seed),
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Campaign B — cancel-during-call
// ─────────────────────────────────────────────────────────────────────────────

async function iterationB(
  h: XcHarness,
  up: Upstream,
  iteration: number,
  seed: number,
): Promise<IterationRow> {
  const prng = new Prng(seed);
  const policy: RefreshPolicy = prng.next() < 0.5
    ? "rotate-reject-reuse"
    : "rotate-reuse-window";
  const latencyMaxMs = prng.int(2, 20);
  h.fake.reset(seed, latencyMaxMs);
  h.fake.refreshPolicy = policy;
  up.reset();
  const actor = await mintActor(h, prng, 0);
  const actors = [actor];
  // One abandoned call plus 0–3 concurrent duplicates from the same device
  // (the app retries when it never saw an answer).
  const ops: Op[] = [{
    index: 0,
    actor: 0,
    kind: "abort",
    startDelayMs: 0,
    abortAfterMs: prng.int(0, 25),
  }];
  const retries = prng.int(0, 3);
  for (let i = 1; i <= retries; i++) {
    ops.push({
      index: i,
      actor: 0,
      kind: "dup",
      startDelayMs: prng.int(0, 30),
    });
  }

  const started = performance.now();
  const results = await Promise.all(ops.map((op) => runOp(h, actor, op)));
  const durationMs = Math.round(performance.now() - started);
  const statuses = results.flatMap((r) => r.statuses);
  const invariants: Invariant[] = [];
  inv(
    invariants,
    "bounded wall time",
    durationMs <= ITERATION_BOUND_MS,
    `${durationMs}ms`,
  );
  inv(
    invariants,
    "no 5xx",
    statuses.every((s) => s < 500 && s > 0),
    JSON.stringify(histogram(statuses)),
  );
  const okReplies = results.flatMap((r) => r.received);
  inv(
    invariants,
    "exactly the GoTrue-minted sessions were produced (abandoned reply included)",
    okReplies.length === up.minted.size || policy === "rotate-reuse-window",
    `replies200=${okReplies.length} minted=${up.minted.size}`,
  );
  inv(
    invariants,
    policy === "rotate-reject-reuse"
      ? "reject-reuse: at most ONE of {abandoned, retries} rotated; the rest are 401"
      : "reuse-window: every reply is a 200 carrying a minted session",
    policy === "rotate-reject-reuse"
      ? (statuses.filter((s) => s === 200).length <= 1 &&
        statuses.every((s) => s === 200 || s === 401))
      : statuses.every((s) => s === 200),
    JSON.stringify(histogram(statuses)),
  );
  // Whatever the client saw, the model has exactly one live session and its
  // newest token rotates.
  const fakeSession = h.fake.sessions.get(actor.sessionId)!;
  const live = await h.handler(
    refreshRequest(nextIp(), fakeSession.refreshToken),
  );
  await live.body?.cancel();
  inv(
    invariants,
    "session survives the abandoned call",
    live.status === 200 && !fakeSession.revoked,
    `newest refresh → ${live.status}`,
  );
  // Observation (not an invariant): did the client keep a token that is now dead?
  const aborted = results[0];
  const clientHeldTokenDead = aborted.clientOutcome === "client-aborted" &&
    aborted.statuses[0] === 200 && policy === "rotate-reject-reuse" &&
    !results.slice(1).some((r) => r.statuses[0] === 200);
  inv(
    invariants,
    "observation: abandoned call rotated upstream while the client kept the old token",
    true,
    `clientAborted=${
      aborted.clientOutcome === "client-aborted"
    } serverRotated=${
      aborted.statuses[0] === 200
    } clientNowHoldsDeadToken=${clientHeldTokenDead}`,
  );
  return {
    campaign: "B",
    iteration,
    seed,
    policy,
    latencyMaxMs,
    actors: actors.map((a) => ({
      id: a.id,
      ip: a.ip,
      sessionId: a.sessionId,
      sharesSessionWith: null,
    })),
    ops,
    results,
    edgeStatusHistogram: histogram(statuses),
    upstream: {
      refreshCalls: up.refreshCalls,
      refreshStatus: up.refreshStatus,
      minted: up.minted.size,
    },
    invariants,
    holds: invariants.every((i) => i.holds),
    durationMs,
    replay: replay("B", seed),
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Campaign F — logout racing refresh across two devices on one session
// ─────────────────────────────────────────────────────────────────────────────

async function iterationF(
  h: XcHarness,
  up: Upstream,
  iteration: number,
  seed: number,
): Promise<IterationRow> {
  const prng = new Prng(seed);
  const policy: RefreshPolicy = prng.next() < 0.5
    ? "rotate-reject-reuse"
    : "rotate-reuse-window";
  const latencyMaxMs = prng.int(0, 20);
  h.fake.reset(seed, latencyMaxMs);
  h.fake.refreshPolicy = policy;
  h.fake.overrides = { logoutDelayMs: prng.int(0, 20) };
  up.reset();
  const device0 = await mintActor(h, prng, 0);
  const device1: Actor = { ...device0, id: 1, ip: nextIp() };
  const actors = [device0, device1];
  const ops: Op[] = prng.shuffle([
    {
      index: 0,
      actor: 0,
      kind: "chain" as OpKind,
      startDelayMs: prng.int(0, 15),
    },
    {
      index: 1,
      actor: 1,
      kind: "logout" as OpKind,
      startDelayMs: prng.int(0, 15),
    },
    {
      index: 2,
      actor: 1,
      kind: "dup" as OpKind,
      startDelayMs: prng.int(0, 15),
    },
    {
      index: 3,
      actor: 0,
      kind: "probe" as OpKind,
      startDelayMs: prng.int(0, 15),
    },
  ]);
  const started = performance.now();
  const results = await Promise.all(
    ops.map((op) => runOp(h, actors[op.actor], op)),
  );
  const durationMs = Math.round(performance.now() - started);
  h.fake.overrides = {};
  const statuses = results.flatMap((r) => r.statuses);
  const invariants: Invariant[] = [];
  inv(
    invariants,
    "bounded wall time",
    durationMs <= ITERATION_BOUND_MS,
    `${durationMs}ms`,
  );
  inv(
    invariants,
    "no 5xx",
    statuses.every((s) => s < 500 && s > 0),
    JSON.stringify(histogram(statuses)),
  );
  const logout = results.find((r) => r.kind === "logout")!;
  inv(
    invariants,
    "logout with a valid bearer is 204",
    logout.statuses[0] === 204,
    `logout=${logout.statuses[0]}`,
  );
  const tokens = tokensOfSession(h, device0.sessionId, actors, results);
  const probeIp = nextIp();
  const bearers = await Promise.all(
    [...tokens.access].map((token) =>
      h.handler(edgeRequest("GET", "/v1/me/access", { ip: probeIp, token }))
        .then(async (r) => {
          await r.body?.cancel();
          return r.status;
        })
    ),
  );
  const refreshes = await Promise.all(
    [...tokens.refresh].map((token) =>
      h.handler(refreshRequest(nextIp(), token)).then(async (r) => {
        await r.body?.cancel();
        return r.status;
      })
    ),
  );
  inv(
    invariants,
    "after logout+refresh settle, EVERY bearer and refresh token of the session is 401",
    bearers.every((s) => s === 401) && refreshes.every((s) => s === 401),
    `bearers=${JSON.stringify(histogram(bearers))} refresh=${
      JSON.stringify(histogram(refreshes))
    } tokens=${tokens.access.size}/${tokens.refresh.size}`,
  );
  const okReplies = results.flatMap((r) => r.received);
  inv(
    invariants,
    "every 200 during the race is a GoTrue-minted session (none forged after revocation)",
    okReplies.every((s) => up.minted.get(s.accessToken) === s.refreshToken),
    `replies200=${okReplies.length} minted=${up.minted.size}`,
  );
  return {
    campaign: "F",
    iteration,
    seed,
    policy,
    latencyMaxMs,
    actors: actors.map((a) => ({
      id: a.id,
      ip: a.ip,
      sessionId: a.sessionId,
      sharesSessionWith: a.id === 0 ? 1 : 0,
    })),
    ops,
    results,
    edgeStatusHistogram: histogram(statuses),
    upstream: {
      refreshCalls: up.refreshCalls,
      refreshStatus: up.refreshStatus,
      minted: up.minted.size,
    },
    invariants,
    holds: invariants.every((i) => i.holds),
    durationMs,
    replay: replay("F", seed),
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Campaign runner + table writer
// ─────────────────────────────────────────────────────────────────────────────

async function runCampaign(
  name: string,
  iterations: number,
  run: (
    h: XcHarness,
    up: Upstream,
    iteration: number,
    seed: number,
  ) => Promise<IterationRow>,
): Promise<IterationRow[]> {
  const { h, up } = await loadStressHarness();
  const rows: IterationRow[] = [];
  for (let i = 0; i < iterations; i++) {
    const seed = (STRESS_SEED + i) >>> 0;
    rows.push(await run(h, up, i, seed));
  }
  const failing = rows.filter((r) => !r.holds);
  const table = {
    campaign: name,
    generatedAt: new Date().toISOString(),
    deno: Deno.version.deno,
    env: { STRESS_SEED, STRESS_ITER, ITERATION_BOUND_MS },
    iterations: rows.length,
    failing: failing.length,
    edgeStatusHistogram: histogram(
      rows.flatMap((r) => r.results.flatMap((x) => x.statuses)),
    ),
    wallTimeMs: {
      total: rows.reduce((sum, r) => sum + r.durationMs, 0),
      max: Math.max(0, ...rows.map((r) => r.durationMs)),
    },
    seedOutcomes: rows.map((r) => ({
      seed: r.seed,
      holds: r.holds,
      broken: r.invariants.filter((i) => !i.holds).map((i) => i.name),
      durationMs: r.durationMs,
      replay: r.replay,
    })),
    rows,
  };
  const path = `${outDir()}campaign_${name}.json`;
  await Deno.writeTextFile(path, JSON.stringify(table, null, 2));
  console.log(
    `[stress ${name}] ${rows.length} iterations, ${failing.length} failing → ${path}`,
  );
  for (const row of failing) {
    const broken = row.invariants.filter((i) => !i.holds);
    console.log(
      `[stress ${name}] seed=${row.seed} BROKEN: ${
        broken.map((i) => `${i.name} (${i.detail})`).join("; ")
      }`,
    );
  }
  return rows;
}

function assertAllHold(name: string, rows: IterationRow[]): void {
  const failing = rows.filter((r) => !r.holds);
  assert(
    failing.length === 0,
    `[stress ${name}] ${failing.length}/${rows.length} seeds broke an invariant: ` +
      failing.slice(0, 5).map((r) => `${r.seed} → ${r.replay}`).join(" | "),
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

Deno.test("stress A: seeded interleavings — dup/chain/abort/logout/probe/garbage/body-error", async () => {
  const rows = await runCampaign("A", STRESS_ITER, iterationA);
  assertAllHold("A", rows);
});

Deno.test("stress B: cancel-during-call — abandoned rotation is neither lost nor duplicated", async () => {
  const rows = await runCampaign(
    "B",
    Math.max(1, Math.round(STRESS_ITER / 3)),
    iterationB,
  );
  assertAllHold("B", rows);
});

Deno.test("stress F: logout racing refresh across two devices on one session", async () => {
  const rows = await runCampaign(
    "F",
    Math.max(1, Math.round(STRESS_ITER / 3)),
    iterationF,
  );
  assertAllHold("F", rows);
});

// Campaign C — per-IP refresh budget and auth-failure budget under a burst.
interface BurstRow {
  campaign: string;
  seed: number;
  ip: string;
  burst: number;
  statuses: Record<string, number>;
  upstreamRefreshCalls: number;
  invariants: Invariant[];
  holds: boolean;
  durationMs: number;
  replay: string;
}

Deno.test("stress C: same-IP burst admits exactly AUTH_REFRESH_LIMIT; 401s charge the auth-failure budget once each", async () => {
  const { h, up } = await loadStressHarness();
  const rows: BurstRow[] = [];
  const seeds = Math.max(1, Math.round(STRESS_ITER / 6));
  for (let i = 0; i < seeds; i++) {
    const seed = (STRESS_SEED + 1_000_000 + i) >>> 0;
    const prng = new Prng(seed);
    h.fake.reset(seed, prng.int(0, 10));
    h.fake.refreshPolicy = "rotate-reuse-window"; // every call succeeds upstream → pure limiter test
    up.reset();
    const actor = await mintActor(h, prng, 0);
    const burst = AUTH_REFRESH_LIMIT * 2;
    const started = performance.now();
    const statuses = await Promise.all(
      Array.from(
        { length: burst },
        () =>
          sleep(prng.int(0, 5)).then(() =>
            h.handler(refreshRequest(actor.ip, actor.refreshToken))
          ).then(
            async (r) => {
              await r.body?.cancel();
              return r.status;
            },
          ),
      ),
    );
    const durationMs = Math.round(performance.now() - started);
    const hist = histogram(statuses);
    const invariants: Invariant[] = [];
    inv(
      invariants,
      "bounded wall time",
      durationMs <= ITERATION_BOUND_MS,
      `${durationMs}ms`,
    );
    inv(
      invariants,
      `exactly ${AUTH_REFRESH_LIMIT} admitted (200), ${
        burst - AUTH_REFRESH_LIMIT
      } refused (429), none 5xx`,
      (hist["200"] ?? 0) === AUTH_REFRESH_LIMIT &&
        (hist["429"] ?? 0) === burst - AUTH_REFRESH_LIMIT,
      JSON.stringify(hist),
    );
    inv(
      invariants,
      "refused requests never reach GoTrue",
      up.refreshCalls === AUTH_REFRESH_LIMIT,
      `gotrue refresh calls=${up.refreshCalls}`,
    );
    rows.push({
      campaign: "C-refresh-budget",
      seed,
      ip: actor.ip,
      burst,
      statuses: hist,
      upstreamRefreshCalls: up.refreshCalls,
      invariants,
      holds: invariants.every((x) => x.holds),
      durationMs,
      replay: replay("C", seed),
    });

    // Auth-failure budget: 30 concurrent garbage refreshes from one IP all
    // reach GoTrue (the budget is peeked up-front, charged by outcome), then
    // the 31st request from that IP is refused before touching GoTrue.
    h.fake.reset(seed + 1, prng.int(0, 10));
    up.reset();
    const badIp = nextIp();
    const t1 = performance.now();
    const bad = await Promise.all(
      Array.from({ length: AUTH_FAILURE_LIMIT }, (_, k) =>
        sleep(prng.int(0, 5))
          .then(() =>
            h.handler(refreshRequest(badIp, `rt-0.0-garbage-${seed}-${k}`))
          )
          .then(async (r) => {
            await r.body?.cancel();
            return r.status;
          })),
    );
    const callsAfterBurst = up.refreshCalls;
    const next = await h.handler(
      refreshRequest(badIp, `rt-0.0-garbage-${seed}-next`),
    );
    await next.body?.cancel();
    const d1 = Math.round(performance.now() - t1);
    const badHist = histogram(bad);
    const inv2: Invariant[] = [];
    inv(inv2, "bounded wall time", d1 <= ITERATION_BOUND_MS, `${d1}ms`);
    inv(
      inv2,
      `${AUTH_FAILURE_LIMIT} garbage refreshes are all 401`,
      (badHist["401"] ?? 0) === AUTH_FAILURE_LIMIT,
      JSON.stringify(badHist),
    );
    inv(
      inv2,
      "each 401 charged the auth-failure budget exactly once → next request is 429 and never reaches GoTrue",
      next.status === 429 && up.refreshCalls === callsAfterBurst &&
        callsAfterBurst === AUTH_FAILURE_LIMIT,
      `next=${next.status} gotrueCalls=${up.refreshCalls} afterBurst=${callsAfterBurst}`,
    );
    rows.push({
      campaign: "C-authfail-budget",
      seed: seed + 1,
      ip: badIp,
      burst: AUTH_FAILURE_LIMIT + 1,
      statuses: { ...badHist, [`next:${next.status}`]: 1 },
      upstreamRefreshCalls: up.refreshCalls,
      invariants: inv2,
      holds: inv2.every((x) => x.holds),
      durationMs: d1,
      replay: replay("C", seed),
    });
  }
  const path = `${outDir()}campaign_C.json`;
  await Deno.writeTextFile(
    path,
    JSON.stringify(
      {
        campaign: "C",
        generatedAt: new Date().toISOString(),
        env: { STRESS_SEED, STRESS_ITER },
        iterations: rows.length,
        failing: rows.filter((r) => !r.holds).length,
        seedOutcomes: rows.map((r) => ({
          seed: r.seed,
          campaign: r.campaign,
          holds: r.holds,
          replay: r.replay,
        })),
        rows,
      },
      null,
      2,
    ),
  );
  console.log(
    `[stress C] ${rows.length} bursts, ${
      rows.filter((r) => !r.holds).length
    } failing → ${path}`,
  );
  const failing = rows.filter((r) => !r.holds);
  assert(
    failing.length === 0,
    `[stress C] ${
      failing.map((r) =>
        `${r.seed}: ${
          r.invariants.filter((i) => !i.holds).map((i) =>
            `${i.name} (${i.detail})`
          ).join("; ")
        }`
      ).join(" | ")
    }`,
  );
});

// Campaign D — clock skew between GoTrue and the edge.
interface SkewRow {
  campaign: string;
  seed: number;
  skewSeconds: number;
  burst: number;
  statuses: Record<string, number>;
  bearerProbe: Record<string, number>;
  expiresAtMinusNow: number[];
  invariants: Invariant[];
  holds: boolean;
  durationMs: number;
  replay: string;
}

const SKEWS_SECONDS = [
  -7_200,
  -3_601,
  -3_600,
  -3_590,
  -1_800,
  -600,
  -30,
  -5,
  0,
  5,
  30,
  600,
  3_600,
  86_400,
];

Deno.test("stress D: clock skew — a 200 never carries a dead bearer; an already-expired upstream session is 503 not 401", async () => {
  const { h, up } = await loadStressHarness();
  const rows: SkewRow[] = [];
  const perSkew = Math.max(1, Math.round(STRESS_ITER / 12));
  for (const skewSeconds of SKEWS_SECONDS) {
    for (let i = 0; i < perSkew; i++) {
      const seed =
        (STRESS_SEED + 2_000_000 + SKEWS_SECONDS.indexOf(skewSeconds) * 10_000 +
          i) >>> 0;
      const prng = new Prng(seed);
      h.fake.reset(seed, prng.int(0, 15));
      h.fake.refreshPolicy = "rotate-reuse-window";
      up.reset();
      const actor = await mintActor(h, prng, 0); // bootstrap happens with clocks in sync
      up.skewSeconds = skewSeconds;
      const burst = prng.int(2, 6);
      const started = performance.now();
      const replies = await Promise.all(
        Array.from({ length: burst }, () =>
          sleep(prng.int(0, 8))
            .then(() => h.handler(refreshRequest(actor.ip, actor.refreshToken)))
            .then(async (r) => ({
              status: r.status,
              body: await readJson(r),
              retryAfter: r.headers.get("retry-after"),
            }))),
      );
      const durationMs = Math.round(performance.now() - started);
      up.skewSeconds = 0;
      const statuses = replies.map((r) => r.status);
      const sessions = replies.map((
        r,
      ) => (r.status === 200 ? sessionOf(r.body) : null));
      const nowSeconds = Math.floor(Date.now() / 1000);
      // Probe every returned bearer against the edge immediately.
      const probeIp = nextIp();
      const bearerProbe = await Promise.all(
        sessions.filter((s): s is NonNullable<typeof s> => s !== null).map((
          s,
        ) =>
          h.handler(
            edgeRequest("GET", "/v1/me/access", {
              ip: probeIp,
              token: s.accessToken,
            }),
          ).then(
            async (r) => {
              await r.body?.cancel();
              return r.status;
            },
          )
        ),
      );
      const invariants: Invariant[] = [];
      inv(
        invariants,
        "bounded wall time",
        durationMs <= ITERATION_BOUND_MS,
        `${durationMs}ms`,
      );
      inv(
        invariants,
        "no 5xx other than 503, no 401 (the token was never refused)",
        statuses.every((s) => s === 200 || s === 503),
        JSON.stringify(histogram(statuses)),
      );
      const upstreamExpired = skewSeconds <= -3_600; // exp = now + 3600 + skew ≤ now
      inv(
        invariants,
        upstreamExpired
          ? "GoTrue answered with an already-expired session → every reply is 503 + Retry-After (retryable, NOT sign-out)"
          : "GoTrue session is live → every reply is 200",
        upstreamExpired
          ? replies.every((r) => r.status === 503 && r.retryAfter !== null)
          : statuses.every((s) => s === 200),
        `statuses=${JSON.stringify(histogram(statuses))} retryAfter=${
          JSON.stringify(replies.map((r) => r.retryAfter))
        }`,
      );
      inv(
        invariants,
        "every 200 reply's bearer authenticates right now (no dead-on-arrival bearer)",
        bearerProbe.every((s) => s === 200),
        JSON.stringify(histogram(bearerProbe)),
      );
      inv(
        invariants,
        "every 200 reply's expiresAt is GoTrue's (skewed) expiry, in the future",
        sessions.every((s) =>
          s === null ||
          (s.expiresAt > nowSeconds &&
            Math.abs(s.expiresAt - (nowSeconds + 3_600 + skewSeconds)) <= 5)
        ),
        JSON.stringify(
          sessions.map((s) => (s ? s.expiresAt - nowSeconds : null)),
        ),
      );
      inv(
        invariants,
        "the refresh token itself stays alive after an expired-session 503 (client can retry, no sign-out)",
        !upstreamExpired ||
          h.fake.sessions.get(actor.sessionId)?.revoked === false,
        `revoked=${h.fake.sessions.get(actor.sessionId)?.revoked}`,
      );
      rows.push({
        campaign: "D",
        seed,
        skewSeconds,
        burst,
        statuses: histogram(statuses),
        bearerProbe: histogram(bearerProbe),
        expiresAtMinusNow: sessions.map((
          s,
        ) => (s ? s.expiresAt - nowSeconds : Number.NaN)),
        invariants,
        holds: invariants.every((x) => x.holds),
        durationMs,
        replay: replay("D", seed),
      });
    }
  }
  const path = `${outDir()}campaign_D.json`;
  await Deno.writeTextFile(
    path,
    JSON.stringify(
      {
        campaign: "D",
        generatedAt: new Date().toISOString(),
        env: { STRESS_SEED, STRESS_ITER },
        skews: SKEWS_SECONDS,
        iterations: rows.length,
        failing: rows.filter((r) => !r.holds).length,
        seedOutcomes: rows.map((r) => ({
          seed: r.seed,
          skewSeconds: r.skewSeconds,
          holds: r.holds,
          statuses: r.statuses,
          replay: r.replay,
        })),
        rows,
      },
      null,
      2,
    ),
  );
  console.log(
    `[stress D] ${rows.length} skew bursts, ${
      rows.filter((r) => !r.holds).length
    } failing → ${path}`,
  );
  const failing = rows.filter((r) => !r.holds);
  assert(
    failing.length === 0,
    `[stress D] ${
      failing.map((r) =>
        `${r.seed} skew=${r.skewSeconds}: ${
          r.invariants.filter((i) => !i.holds).map((i) =>
            `${i.name} (${i.detail})`
          ).join("; ")
        }`
      ).join(" | ")
    }`,
  );
});

// Campaign E — GoTrue hangs or drops connections under a burst.
interface OutageRow {
  campaign: string;
  seed: number;
  mode: "hang" | "connection-reset";
  deadlineMs: number;
  burst: number;
  statuses: Record<string, number>;
  retryAfter: Record<string, number>;
  upstreamAttempts: number;
  recovered: number;
  invariants: Invariant[];
  holds: boolean;
  durationMs: number;
  replay: string;
}

Deno.test("stress E: GoTrue hang / connection reset under a burst — bounded by the deadline, 503 + Retry-After, token survives", async () => {
  const { h, up } = await loadStressHarness();
  const rows: OutageRow[] = [];
  const deadlineMs = 250;
  const previous = Deno.env.get("AUTH_UPSTREAM_TIMEOUT_MS");
  Deno.env.set("AUTH_UPSTREAM_TIMEOUT_MS", String(deadlineMs));
  try {
    const seeds = Math.max(1, Math.round(STRESS_ITER / 8));
    for (let i = 0; i < seeds; i++) {
      for (const mode of ["hang", "connection-reset"] as const) {
        const seed =
          (STRESS_SEED + 3_000_000 + i * 2 + (mode === "hang" ? 0 : 1)) >>> 0;
        const prng = new Prng(seed);
        h.fake.reset(seed, prng.int(0, 5));
        h.fake.refreshPolicy = "rotate-reject-reuse";
        up.reset();
        const actor = await mintActor(h, prng, 0);
        const ips = [nextIp(), nextIp()]; // 40 requests across 2 IPs stays under the 30/IP budget
        const burst = 40;
        up.mode = mode;
        const started = performance.now();
        const replies = await Promise.all(
          Array.from({ length: burst }, (_, k) =>
            sleep(prng.int(0, 10))
              .then(() =>
                h.handler(refreshRequest(ips[k % 2], actor.refreshToken))
              )
              .then(async (r) => {
                await r.body?.cancel();
                return {
                  status: r.status,
                  retryAfter: r.headers.get("retry-after"),
                };
              })),
        );
        const durationMs = Math.round(performance.now() - started);
        up.mode = "pass";
        const attempts = up.refreshCalls;
        // Recovery: the very same refresh token must still rotate once GoTrue is back.
        const recovered = await h.handler(
          refreshRequest(nextIp(), actor.refreshToken),
        );
        await recovered.body?.cancel();
        const statuses = histogram(replies.map((r) => r.status));
        const invariants: Invariant[] = [];
        inv(
          invariants,
          `whole burst settles within deadline + slack (${deadlineMs}ms + 1500ms)`,
          durationMs <= deadlineMs + 1_500,
          `${durationMs}ms`,
        );
        inv(
          invariants,
          "every reply is 503 with Retry-After (never 401 → no forced sign-out, never 500)",
          replies.every((r) => r.status === 503 && r.retryAfter !== null),
          `${JSON.stringify(statuses)} retryAfter=${
            JSON.stringify(
              histogram(replies.map((r) => r.retryAfter ?? "none")),
            )
          }`,
        );
        inv(
          invariants,
          mode === "hang"
            ? "a hang is not retried inside the deadline (exactly one upstream attempt per request)"
            : "connection faults are retried only while the deadline allows (≤ 2 attempts per request at 250ms)",
          mode === "hang"
            ? attempts === burst
            : attempts >= burst && attempts <= burst * 2,
          `attempts=${attempts} burst=${burst}`,
        );
        inv(
          invariants,
          "the refresh token survives the outage and rotates once GoTrue is back",
          recovered.status === 200,
          `recovery → ${recovered.status}`,
        );
        rows.push({
          campaign: "E",
          seed,
          mode,
          deadlineMs,
          burst,
          statuses,
          retryAfter: histogram(replies.map((r) => r.retryAfter ?? "none")),
          upstreamAttempts: attempts,
          recovered: recovered.status,
          invariants,
          holds: invariants.every((x) => x.holds),
          durationMs,
          replay: replay("E", seed),
        });
      }
    }
  } finally {
    up.mode = "pass";
    if (previous === undefined) Deno.env.delete("AUTH_UPSTREAM_TIMEOUT_MS");
    else Deno.env.set("AUTH_UPSTREAM_TIMEOUT_MS", previous);
  }
  const path = `${outDir()}campaign_E.json`;
  await Deno.writeTextFile(
    path,
    JSON.stringify(
      {
        campaign: "E",
        generatedAt: new Date().toISOString(),
        env: { STRESS_SEED, STRESS_ITER, deadlineMs },
        iterations: rows.length,
        failing: rows.filter((r) => !r.holds).length,
        seedOutcomes: rows.map((r) => ({
          seed: r.seed,
          mode: r.mode,
          holds: r.holds,
          statuses: r.statuses,
          upstreamAttempts: r.upstreamAttempts,
          durationMs: r.durationMs,
          replay: r.replay,
        })),
        rows,
      },
      null,
      2,
    ),
  );
  console.log(
    `[stress E] ${rows.length} outage bursts, ${
      rows.filter((r) => !r.holds).length
    } failing → ${path}`,
  );
  const failing = rows.filter((r) => !r.holds);
  assert(
    failing.length === 0,
    `[stress E] ${
      failing.map((r) =>
        `${r.seed} ${r.mode}: ${
          r.invariants.filter((i) => !i.holds).map((i) =>
            `${i.name} (${i.detail})`
          ).join("; ")
        }`
      ).join(" | ")
    }`,
  );
});

// Summary table (Deno runs tests in file order; this one is last).
Deno.test("stress: write summary.json", async () => {
  const dir = outDir();
  const campaigns: Array<Record<string, unknown>> = [];
  let scenarios = 0;
  let failing = 0;
  for (const name of ["A", "B", "F", "C", "D", "E"]) {
    const path = `${dir}campaign_${name}.json`;
    const stat = await Deno.stat(path).catch(() => null);
    if (!stat) continue;
    const table = JSON.parse(await Deno.readTextFile(path)) as {
      iterations: number;
      failing: number;
      seedOutcomes: Array<{ seed: number; holds: boolean }>;
    };
    scenarios += table.iterations;
    failing += table.failing;
    campaigns.push({
      campaign: name,
      iterations: table.iterations,
      failing: table.failing,
      failingSeeds: table.seedOutcomes.filter((s) => !s.holds).map((s) =>
        s.seed
      ),
      file: `campaign_${name}.json`,
    });
  }
  const summary = {
    unit: "route-post-v1-auth-refresh",
    lens: "concurrency",
    generatedAt: new Date().toISOString(),
    deno: Deno.version,
    env: { STRESS_SEED, STRESS_ITER, ITERATION_BOUND_MS },
    scenariosExecuted: scenarios,
    failing,
    campaigns,
  };
  await Deno.writeTextFile(
    `${dir}summary.json`,
    JSON.stringify(summary, null, 2),
  );
  console.log(
    `[stress] summary → ${dir}summary.json (${scenarios} iterations, ${failing} failing)`,
  );
  assert(
    campaigns.length === 6,
    `expected 6 campaign tables, found ${campaigns.length}`,
  );
});
