"""Frozen integration-adversary launcher — generated by make_adversary_launcher.py; do not hand-edit."""
import asyncio
import sys

sys.path.insert(0, '/home/ubuntu/repos/Pickle-Sensei/.devin/skills/production-program')
import program_lib  # noqa: E402

FANOUT_ID = 'adv-2-offline-billing'
HEAD_SHA = '2994371e1c5edf9a1e9bb12f6c6e4751e3fb4ea1'
INTEGRATION_BRANCH = 'devin/1788854799-production-program-integration'
OUT_ROOT = '/home/ubuntu/repos/Pickle-Sensei/.devin/program/ledger'
MODE = None
MINUTES = 60
AREAS = ['backend-sql-rls', 'billing-entitlement', 'charging-permits', 'offline-lease', 'security-privacy', 'state-consistency', 'sync-outbox-persistence', 'deletion-managed-media']
LIB_VERSION = '2026-09-08.8'


async def main():
    if program_lib.LIB_VERSION != LIB_VERSION:
        raise SystemExit("program_lib changed since this launcher was frozen; regenerate the launcher")
    runtime = program_lib.Runtime(
        register_workflow=register_workflow,
        agent=agent,
        log=log,
        agent_error=WorkflowAgentError,
    )
    summary = await program_lib.run_adversary_fanout(
        fanout_id=FANOUT_ID,
        head_sha=HEAD_SHA,
        integration_branch=INTEGRATION_BRANCH,
        out_root=OUT_ROOT,
        runtime=runtime,
        areas=AREAS,
        mode=MODE,
        minutes=MINUTES,
    )
    log("ADVERSARY FANOUT RESULT " + program_lib.dump(summary))


asyncio.run(main())
