"""Frozen integration-adversary launcher — generated by make_adversary_launcher.py; do not hand-edit."""
import asyncio
import sys

sys.path.insert(0, '/home/ubuntu/repos/Pickle-Sensei/.devin/skills/production-program')
import program_lib  # noqa: E402

FANOUT_ID = 'adv-1'
HEAD_SHA = '30a4065036a917514fb4984fde73f87867f38619'
INTEGRATION_BRANCH = 'devin/1788854799-production-program-integration'
OUT_ROOT = '/home/ubuntu/repos/Pickle-Sensei/.devin/program/ledger'
MODE = None
MINUTES = 60
AREAS = ['auth-session', 'backend-sql-rls', 'billing-entitlement', 'sync-outbox-persistence', 'charging-permits', 'offline-lease', 'deletion-managed-media', 'import-media-capture', 'analysis-scoring', 'ui-flows-a11y', 'networking-recovery', 'state-consistency', 'security-privacy', 'release-config', 'performance-bounds', 'native-bridge-contract', 'e2e-journeys']
LIB_VERSION = '2026-09-08.7'


async def main():
    if program_lib.LIB_VERSION != LIB_VERSION:
        raise SystemExit("program_lib changed since this launcher was frozen; regenerate the launcher")
    runtime = program_lib.Runtime(
        register_workflow=register_workflow,
        agent=agent,
        log=log,
        agent_error=WorkflowAgentError,
    )
    summary = await program_lib.run_adversary_fanout(
        fanout_id=FANOUT_ID,
        head_sha=HEAD_SHA,
        integration_branch=INTEGRATION_BRANCH,
        out_root=OUT_ROOT,
        runtime=runtime,
        areas=AREAS,
        mode=MODE,
        minutes=MINUTES,
    )
    log("ADVERSARY FANOUT RESULT " + program_lib.dump(summary))


asyncio.run(main())
