"""Frozen launcher — generated by make_launcher.py; do not hand-edit."""
import asyncio
import sys

sys.path.insert(0, '/home/ubuntu/repos/Pickle-Sensei/.devin/skills/production-program')
import program_lib  # noqa: E402

PACKAGE_ID = 'W06-01'
BASE_SHA = '608bf7b4d6d214740ec3fdc943b20ca9ffe78a57'
INTEGRATION_BRANCH = 'devin/1788854799-production-program-integration'
MANIFEST_PATH = '/home/ubuntu/repos/Pickle-Sensei/.devin/program/manifest.json'
MANIFEST_SHA256 = '68877e2f414d8b91116c87232cd7e94e883276892c2d913cfb2d7436788c7d11'
OUT_ROOT = '/home/ubuntu/repos/Pickle-Sensei/.devin/program/ledger'
WAVE_ID = 'wave-2'
MAX_ROUNDS = 2
MODE = None
START_ROUND = 3
PRIOR = {'branch': 'devin/pp/w06-01/impl-r2', 'head_sha': '9c47cf079d56620e4e66699bf31ddda86c2a283b', 'findings': {'judge': ['adversarial P0/P1 breaks: 1'], 'review_blocking': [], 'review_invariants': [], 'adversary_breaks': [{'expected': 'A deterministic, order-independent result for the same multiset of inputs (e.g. tie-break the surviving duplicate by the recencyOrder keys, or document/abstain), so identical inputs rank identically on every plane.', 'observed': 'VERIFIED: rows {id A, 10:00, score 9} then {id A, 11:00, score 3} -> rating 9 / Diamond; reversed input -> rating 3 / Bronze. SQL (shots_pkey keeps the first stored row) = 9. TS matches SQL only in arrival order; the reversed permutation of the identical multiset diverges (rating 3 vs 9, tier bronze vs diamond).', 'repro': "cd packages/shared-types && npx vitest run src/__tests__/attack.w06_01.playerRank.boundaries.test.ts -t 'replayed id with conflicting content'  (exit 1); cross-plane: PICKLE_AUDIT_PG_URL=postgres://postgres:pg@127.0.0.1:55432/postgres deno test -A --config supabase/functions/api/__wf__/deno.json supabase/functions/api/__wf__/attack_w06_01_cross_plane.test.ts --filter 'replayed id with conflicting content'", 'severity': 'P1', 'test_file': 'packages/shared-types/src/__tests__/attack.w06_01.playerRank.boundaries.test.ts; supabase/functions/api/__wf__/attack_w06_01_cross_plane.test.ts', 'title': "computePlayerRank is input-order dependent for a replayed id with conflicting content (first-seen wins), contradicting the definition's own 'input order does not matter' / count-once contract"}], 'adversary_branch': 'devin/pp/w06-01/attack-9c47cf07'}}


async def main():
    manifest = program_lib.load_manifest(MANIFEST_PATH)
    if manifest["manifest_sha256"] != MANIFEST_SHA256:
        raise SystemExit("manifest changed since this launcher was frozen; regenerate the launcher")
    runtime = program_lib.Runtime(
        register_workflow=register_workflow,
        agent=agent,
        log=log,
        agent_error=WorkflowAgentError,
    )
    record = await program_lib.run_package(
        package_id=PACKAGE_ID,
        base_sha=BASE_SHA,
        integration_branch=INTEGRATION_BRANCH,
        manifest_path=MANIFEST_PATH,
        out_root=OUT_ROOT,
        runtime=runtime,
        max_rounds=MAX_ROUNDS,
        mode=MODE,
        wave_id=WAVE_ID,
        start_round=START_ROUND,
        prior=PRIOR,
    )
    log("RESULT " + program_lib.dump({k: record.get(k) for k in ("package_id", "status", "candidate", "agent_counts")}))


asyncio.run(main())
