"""Frozen launcher — generated by make_launcher.py; do not hand-edit."""
import asyncio
import sys

sys.path.insert(0, '/home/ubuntu/repos/Pickle-Sensei/.devin/skills/production-program')
import program_lib  # noqa: E402

PACKAGE_ID = 'W06-06'
BASE_SHA = '42291369fc4387571ac8821410353e0f99404484'
INTEGRATION_BRANCH = 'devin/1788854799-production-program-integration'
MANIFEST_PATH = '/home/ubuntu/repos/Pickle-Sensei/.devin/program/manifest.json'
MANIFEST_SHA256 = '68877e2f414d8b91116c87232cd7e94e883276892c2d913cfb2d7436788c7d11'
OUT_ROOT = '/home/ubuntu/repos/Pickle-Sensei/.devin/program/ledger'
WAVE_ID = 'wave-1'
MAX_ROUNDS = 2
MODE = None
START_ROUND = 1
PRIOR = None


async def main():
    manifest = program_lib.load_manifest(MANIFEST_PATH)
    if manifest["manifest_sha256"] != MANIFEST_SHA256:
        raise SystemExit("manifest changed since this launcher was frozen; regenerate the launcher")
    runtime = program_lib.Runtime(
        register_workflow=register_workflow,
        agent=agent,
        log=log,
        agent_error=WorkflowAgentError,
    )
    record = await program_lib.run_package(
        package_id=PACKAGE_ID,
        base_sha=BASE_SHA,
        integration_branch=INTEGRATION_BRANCH,
        manifest_path=MANIFEST_PATH,
        out_root=OUT_ROOT,
        runtime=runtime,
        max_rounds=MAX_ROUNDS,
        mode=MODE,
        wave_id=WAVE_ID,
        start_round=START_ROUND,
        prior=PRIOR,
    )
    log("RESULT " + program_lib.dump({k: record.get(k) for k in ("package_id", "status", "candidate", "agent_counts")}))


asyncio.run(main())
