"""Frozen wave launcher — generated by make_wave_launcher.py; do not hand-edit."""
import asyncio
import sys

sys.path.insert(0, '/home/ubuntu/repos/Pickle-Sensei/.devin/skills/production-program')
import program_lib  # noqa: E402

WAVE_ID = 'wave-4'
BASE_SHA = 'd8e5db3eb346b651e4ce04cc997178abcbed56fe'
INTEGRATION_BRANCH = 'codex/production-continuation-20260907'
MANIFEST_PATH = '/home/ubuntu/repos/Pickle-Sensei/.devin/program/manifest.json'
MANIFEST_SHA256 = '07ab317e3f2f9831263e88eb257cfc96c4dd57d73f84c6f123d540615bc0a4db'
OUT_ROOT = '/home/ubuntu/repos/Pickle-Sensei/.devin/program/ledger'
MODE = None
SERIAL_GROUP_LIMIT = 5
PACKAGES = [{'package_id': 'W01-03', 'max_rounds': 2, 'start_round': 1, 'prior': None}, {'package_id': 'W01-04', 'max_rounds': 2, 'start_round': 1, 'prior': None}, {'package_id': 'W02-01', 'max_rounds': 2, 'start_round': 3, 'prior': {'branch': 'devin/pp/w02-01/impl-r2', 'head_sha': '7a44617f8f47d0068081c5db36668a5e16340f7d', 'findings': {'judge': ['impl: W02-01-AC2 status FAIL']}}}, {'package_id': 'W05-02', 'max_rounds': 2, 'start_round': 1, 'prior': None}, {'package_id': 'W07-03', 'max_rounds': 2, 'start_round': 1, 'prior': None}, {'package_id': 'W07-06', 'max_rounds': 2, 'start_round': 1, 'prior': None}, {'package_id': 'W11-01', 'max_rounds': 2, 'start_round': 1, 'prior': None}, {'package_id': 'P0-04', 'max_rounds': 2, 'start_round': 1, 'prior': None}, {'package_id': 'W02-02', 'max_rounds': 2, 'start_round': 1, 'prior': None}, {'package_id': 'W09-02', 'max_rounds': 2, 'start_round': 1, 'prior': None}, {'package_id': 'P0-03', 'max_rounds': 2, 'start_round': 1, 'prior': None}]


async def main():
    manifest = program_lib.load_manifest(MANIFEST_PATH)
    if manifest["manifest_sha256"] != MANIFEST_SHA256:
        raise SystemExit("manifest changed since this launcher was frozen; regenerate the launcher")
    runtime = program_lib.Runtime(
        register_workflow=register_workflow,
        agent=agent,
        log=log,
        agent_error=WorkflowAgentError,
    )
    summary = await program_lib.run_wave(
        wave_id=WAVE_ID,
        packages=PACKAGES,
        base_sha=BASE_SHA,
        integration_branch=INTEGRATION_BRANCH,
        manifest_path=MANIFEST_PATH,
        out_root=OUT_ROOT,
        runtime=runtime,
        mode=MODE,
        serial_group_limit=SERIAL_GROUP_LIMIT,
    )
    log("WAVE RESULT " + program_lib.dump(summary))


asyncio.run(main())
