"""Frozen wave launcher — generated by make_wave_launcher.py; do not hand-edit."""
import asyncio
import sys

sys.path.insert(0, '/home/ubuntu/repos/Pickle-Sensei/.devin/skills/production-program')
import program_lib  # noqa: E402

WAVE_ID = 'wave-6'
BASE_SHA = 'f2ab4e31999267dc5cdd2c6cbe1d4348613d3752'
INTEGRATION_BRANCH = 'codex/production-continuation-20260907'
MANIFEST_PATH = '/home/ubuntu/repos/Pickle-Sensei/.devin/program/manifest.json'
MANIFEST_SHA256 = '2623ed2d18a27e4d21c29199165a9709170cc424b39100bfcf4115bf75e9535e'
OUT_ROOT = '/home/ubuntu/repos/Pickle-Sensei/.devin/program/ledger'
MODE = None
SERIAL_GROUP_LIMIT = 3
PACKAGES = [{'package_id': 'INT-01', 'max_rounds': 2, 'start_round': 1, 'prior': None}, {'package_id': 'INT-03', 'max_rounds': 2, 'start_round': 1, 'prior': None}, {'package_id': 'INT-04', 'max_rounds': 2, 'start_round': 1, 'prior': None}, {'package_id': 'INT-05', 'max_rounds': 2, 'start_round': 1, 'prior': None}, {'package_id': 'INT-06', 'max_rounds': 2, 'start_round': 1, 'prior': None}, {'package_id': 'INT-07', 'max_rounds': 2, 'start_round': 1, 'prior': None}, {'package_id': 'INT-10', 'max_rounds': 2, 'start_round': 1, 'prior': None}, {'package_id': 'INT-11', 'max_rounds': 2, 'start_round': 1, 'prior': None}, {'package_id': 'INT-12', 'max_rounds': 2, 'start_round': 1, 'prior': None}, {'package_id': 'INT-13', 'max_rounds': 2, 'start_round': 1, 'prior': None}, {'package_id': 'INT-14', 'max_rounds': 2, 'start_round': 1, 'prior': None}, {'package_id': 'INT-15', 'max_rounds': 2, 'start_round': 1, 'prior': None}, {'package_id': 'INT-16', 'max_rounds': 2, 'start_round': 1, 'prior': None}]


async def main():
    manifest = program_lib.load_manifest(MANIFEST_PATH)
    if manifest["manifest_sha256"] != MANIFEST_SHA256:
        raise SystemExit("manifest changed since this launcher was frozen; regenerate the launcher")
    runtime = program_lib.Runtime(
        register_workflow=register_workflow,
        agent=agent,
        log=log,
        agent_error=WorkflowAgentError,
    )
    summary = await program_lib.run_wave(
        wave_id=WAVE_ID,
        packages=PACKAGES,
        base_sha=BASE_SHA,
        integration_branch=INTEGRATION_BRANCH,
        manifest_path=MANIFEST_PATH,
        out_root=OUT_ROOT,
        runtime=runtime,
        mode=MODE,
        serial_group_limit=SERIAL_GROUP_LIMIT,
    )
    log("WAVE RESULT " + program_lib.dump(summary))


asyncio.run(main())
