"""Frozen wave launcher — generated by make_wave_launcher.py; do not hand-edit."""
import asyncio
import sys

sys.path.insert(0, '/home/ubuntu/repos/Pickle-Sensei/.devin/skills/production-program')
import program_lib  # noqa: E402

WAVE_ID = 'wave-2b'
BASE_SHA = '55d80326bca44a25550855c2be6f755370493e0f'
INTEGRATION_BRANCH = 'devin/1788854799-production-program-integration'
MANIFEST_PATH = '/home/ubuntu/repos/Pickle-Sensei/.devin/program/manifest.json'
MANIFEST_SHA256 = '68877e2f414d8b91116c87232cd7e94e883276892c2d913cfb2d7436788c7d11'
OUT_ROOT = '/home/ubuntu/repos/Pickle-Sensei/.devin/program/ledger'
MODE = None
PACKAGES = [{'package_id': 'P0-02', 'max_rounds': 1, 'start_round': 1, 'prior': None}]


async def main():
    manifest = program_lib.load_manifest(MANIFEST_PATH)
    if manifest["manifest_sha256"] != MANIFEST_SHA256:
        raise SystemExit("manifest changed since this launcher was frozen; regenerate the launcher")
    runtime = program_lib.Runtime(
        register_workflow=register_workflow,
        agent=agent,
        log=log,
        agent_error=WorkflowAgentError,
    )
    summary = await program_lib.run_wave(
        wave_id=WAVE_ID,
        packages=PACKAGES,
        base_sha=BASE_SHA,
        integration_branch=INTEGRATION_BRANCH,
        manifest_path=MANIFEST_PATH,
        out_root=OUT_ROOT,
        runtime=runtime,
        mode=MODE,
    )
    log("WAVE RESULT " + program_lib.dump(summary))


asyncio.run(main())
