"""Frozen wave launcher — generated by make_wave_launcher.py; do not hand-edit."""
import asyncio
import sys

sys.path.insert(0, '/home/ubuntu/repos/Pickle-Sensei/.devin/skills/production-program')
import program_lib  # noqa: E402

WAVE_ID = 'wave-14-keep'
BASE_SHA = '2994371e1c5edf9a1e9bb12f6c6e4751e3fb4ea1'
INTEGRATION_BRANCH = 'devin/1788854799-production-program-integration'
MANIFEST_PATH = '/home/ubuntu/repos/Pickle-Sensei/.devin/program/manifest.json'
MANIFEST_SHA256 = '2623ed2d18a27e4d21c29199165a9709170cc424b39100bfcf4115bf75e9535e'
OUT_ROOT = '/home/ubuntu/repos/Pickle-Sensei/.devin/program/ledger'
MODE = None
SERIAL_GROUP_LIMIT = 5
PACKAGES = [{'package_id': 'W04-02', 'max_rounds': 2, 'start_round': 1, 'prior': None, 'competing': 1}]


async def main():
    manifest = program_lib.load_manifest(MANIFEST_PATH)
    if manifest["manifest_sha256"] != MANIFEST_SHA256:
        raise SystemExit("manifest changed since this launcher was frozen; regenerate the launcher")
    runtime = program_lib.Runtime(
        register_workflow=register_workflow,
        agent=agent,
        log=log,
        agent_error=WorkflowAgentError,
    )
    summary = await program_lib.run_wave(
        wave_id=WAVE_ID,
        packages=PACKAGES,
        base_sha=BASE_SHA,
        integration_branch=INTEGRATION_BRANCH,
        manifest_path=MANIFEST_PATH,
        out_root=OUT_ROOT,
        runtime=runtime,
        mode=MODE,
        serial_group_limit=SERIAL_GROUP_LIMIT,
    )
    log("WAVE RESULT " + program_lib.dump(summary))


asyncio.run(main())
